### ISSUE TITLE
Feature request: Assume role for API calls

### ISSUE THREAD

**Issue by JeroennC** [jenkinsci/amazon-ecs-plugin#103]
Hi,

I have a use case where I would like to deploy ECS agents in account B, from my jenkins master in account A. While leaving out credentials will use account A's role accurately, the plugin is not able to assume a role in account B without supplying the credentials to Jenkins.

It would be nice if a role ARN can be specified for the plugin's AWS client, which is then used for all actions, as a step after the initial authorization:

1. Get AWS API access using credentials if specified, otherwise automatically use role
2. If an assume role ARN is specified, assume this role to do further API actions.

What do you think of this addition?

**Comment by webratz** [comment]
Sounds like a useful addition to me.
The ARN definition should be on the "Cloud" level as the current credentials config is, as then one could use targets in multiple accounts, which is especially interesting for Fargate

**Comment by webratz** [comment]
I still think this would be useful. So if someone wants to create a PR... :)
