### ISSUE TITLE
Default Docker image in Docker Hub was changed

### ISSUE THREAD

**Issue by Bryksin** [jenkinsci/amazon-ecs-plugin#110]
After plugin installation the `ECS agent templates` -> `Docker Image` contains already pre-set default value of: `jenkinsci/jnlp-slave`
However, if you visit the [Hub page](https://hub.docker.com/r/jenkinsci/jnlp-slave/), it stated that this image is deprecated and it is suggested to use new [Hub](https://hub.docker.com/r/jenkins/jnlp-slave/) `jenkins/jnlp-slave` 

So need to replace default value to the new recommended image URL
Additionally, update info hint on the settings page which is reflected in `help-image.html` file

**Comment by markyjackson-taulia** [comment]
Fix will go out in the next release. Thanks kindly for bringing this to our attn..
