### ISSUE TITLE
Declarative Pipeline Not Working

### ISSUE THREAD

**Issue by EdisonHarada** [jenkinsci/amazon-ecs-plugin#116]
Hi,

I really liked this plugin and I ran a few tests and it worked pretty well. But I'm trying now to run a pipeline and I can't manage to make it work.
I always receive this error:
```
Started by user Admin
Running in Durability level: MAX_SURVIVABILITY
[Pipeline] Start of Pipeline
[Pipeline] stage
[Pipeline] { (Test)
[Pipeline] ecsTaskTemplate
[Pipeline] // ecsTaskTemplate
[Pipeline] }
[Pipeline] // stage
[Pipeline] End of Pipeline
ERROR: Cloud does not exist: cloud-default
Finished: FAILURE
```

The pipeline that I'm trying to run is:
```
pipeline {
  agent none

  stages {
    stage('Test') {
        agent {
            ecs {
                inheritFrom 'ecs-label'
            }
        }
        steps {
            sh 'echo hello'
        }
    }
  }
}
```

I also tried to add: "cloud 'ecs'", but didn't work:
```
        agent {
            ecs {
                cloud 'ecs'
                inheritFrom 'ecs-label'
            }
        }
```
And the error was the same, just changed the name of the cloud:
`ERROR: Cloud does not exist: ecs`

My configuration is this:
![Error](https://user-images.githubusercontent.com/5961396/60730829-52f7a800-9f46-11e9-8ef7-79a55589922a.png)

Could you guys help me?

**Comment by tarunarora20** [comment]
Add label in your pipeline and it will automatically start picking the cloud. However it does not allow to override any params after that i.e. image, cpu, etc

**Comment by chb0github** [comment]
@EdisonHarada  - How about you not close an issue with no explanation.

**Comment by chb0github** [comment]
I get other issues too - see #139
