### ISSUE TITLE
Feature request: Add support for IPC Host mode

### ISSUE THREAD

**Issue by rafael-anachoreta** [jenkinsci/amazon-ecs-plugin#118]
Starting November 2018, Amazon ECS added support for IPC modes docker flags - announcement [here](https://aws.amazon.com/about-aws/whats-new/2018/10/amazon-ecs-now-allows-two-additional-docker-flags-/).

My use case is that I've been running some Cypress tests on Docker using amazon-ecs-plugin and at times [my runs will crash](https://docs.cypress.io/guides/references/error-messages.html#The-Chromium-Renderer-process-just-crashed). The documented [workaround for it is to use ipc=host](https://github.com/cypress-io/cypress/issues/350#issuecomment-267704772) when running the container, but I can't do that right now.

So it would be really great if the plugin allowed to make use of this added capability. What do you think? 🙏

**Comment by webratz** [comment]
Feel free to open a PR to add this additional parameter

**Comment by rafael-anachoreta** [comment]
I'll close as, I although I haven't really had the time to submit the PR, I know what needs to be done.

Thanks @webratz
