### ISSUE TITLE
Best practice of running docker build

### ISSUE THREAD

**Issue by jinwg** [jenkinsci/amazon-ecs-plugin#119]
It seems Docker-in-Docker is only option to make docker build workings with this plugin, but still need lots of setting to make sure the build work correctly, just curious about if anyone has any best practice/advice can be shared?

**Comment by webratz** [comment]
You could also mount the hosts docker socket into the containers. (Docker by docker)

**Comment by jinwg** [comment]
thanks @webratz,   i found best solution is not avoid the Docker daemon.  lots of open source tools like Kaniko really did awesome work.
