### ISSUE TITLE
Speedup ECS slave provisioning / do not wait for available executor

### ISSUE THREAD

**Issue by squalou** [jenkinsci/amazon-ecs-plugin#120]
I've been using this plugin for 2 years now, and I still have this issue, and it's even been reported as 'getting worse' by my colleagues. I'm probably missing something here.

Let me explain.

Let's say I have one job running, in a slave named 'ecs-slave-1234' provisioned by ECS plugin, based on the Label 'slave'. (Label in the sens of ECS plugin configuration, and 'node' in the sense of the pipeline)

Then I trigger another job, with the same node('slave')

In the job's console I see 

`Waiting for next available executor on ‘ecs-slave-1234’`

Then it ... waits ... as if it anted to reuse the provisioned one, even if it should be a disposable slave.

In jenkins logs it ends up with logs below (with origin slaves name, slightly different than in my explanation here)

Is there a way to tell Jenkins *never* to reuse an existing executor ?

It sometimes waits up to 3 minutes beofre deciding it sould provision something. A real pain.

I'm using Jenkins LTS 2.176.1
ECS Plugin 1.20

Thank you ! 

```
Jul 16, 2019 10:42:41 AM com.cloudbees.jenkins.plugins.amazonecs.ECSCloud provision
INFO: Asked to provision 1 agent(s) for: jenkins-slave
Jul 16, 2019 10:42:41 AM com.cloudbees.jenkins.plugins.amazonecs.ECSCloud provision
INFO: In provisioning : []
Jul 16, 2019 10:42:41 AM com.cloudbees.jenkins.plugins.amazonecs.ECSCloud provision
INFO: Excess workload after pending ECS agents: 1
Jul 16, 2019 10:42:41 AM com.cloudbees.jenkins.plugins.amazonecs.ECSCloud provision
INFO: Will provision ECS Agent jenkins-slave, for label: jenkins-slave
Jul 16, 2019 10:42:41 AM hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
INFO: Started provisioning ECS Agent jenkins-slave from factory-slaves with 1 executors. Remaining excess workload: -0.289
Jul 16, 2019 10:42:51 AM hudson.slaves.NodeProvisioner$2 run
INFO: ECS Agent jenkins-slave provisioning successfully completed. We have now 3 computer(s)```

**Comment by squalou** [comment]
(in case it makes a difference : I use scipted pipelines, not declarative pipelines, out of an old habit, being using pipelines since they appeared)

**Comment by webratz** [comment]
Afaik the plugin does not get passed the information on the total target number by Jenkins, so some tricks had to be done to make it semi parallel.
See also: https://github.com/jenkinsci/amazon-ecs-plugin#my-parallel-jobs-dont-start-at-the-same-time and https://github.com/jenkinsci/amazon-ecs-plugin/issues/85
Jenkins itself does not distinguish between disposable and long-living slaves.

Anyway: If you have a good idea to make that smoother I'm always happy to review a PR

**Comment by squalou** [comment]
I'd be more than happy to contribute if I can (which is far from sure :) ) 
What I mostly don't know is how Jenkins decides it should wait for an executor on a given 'computer', or that it has waited enough and should 'do something'

From the logs, there's this story of an apparently computed 'workload', than when in excess must be dealt with. Maybe it's time-weighted so that the more a job waits the more an action must be taken .. ?

Any idea where I should look for this ?

**Comment by webratz** [comment]
I think the explanation on what Jenkins does is here: https://github.com/jenkinsci/jenkins/blob/399c8ba40ab9ccab8e70dcacfdd396b0c2e654d7/core/src/main/java/hudson/slaves/NodeProvisioner.java#L622

**Comment by squalou** [comment]
cool, thank you

**Comment by squalou** [comment]
I'm currently trying these options :

` -Dhudson.slaves.NodeProvisioner.MARGIN=100 -Dhudson.slaves.NodeProvisioner.MARGIN0=1.00  -Dhudson.slaves.NodeProvisioner.MARGIN_DECAY=1.00`

it's over aggressive, allows "calcThresholdMargin" to always return 1
then `if (excessWorkload > 1 - m)` (where m = calcThresholdMargin ) has maximum chances of being true.
Let's see if no side effects appear, but in my setup with one job = one ecs slave, should work fie enough.
Else I'll revert to the vaues you provide in the readme.

Thank you again !

**Comment by webratz** [comment]
Just as a reference, this is the setting i use
`-Dhudson.slaves.NodeProvisioner.initialDelay=0 -Dhudson.slaves.NodeProvisioner.MARGIN=50 -Dhudson.slaves.NodeProvisioner.MARGIN0=0.85`

**Comment by rismoney** [comment]
those -D settings are applied on jenkins master or slave?

**Comment by webratz** [comment]
master
