### ISSUE TITLE
How to share docker cache across slaves

### ISSUE THREAD

**Issue by Naveen1836** [jenkinsci/amazon-ecs-plugin#121]
Hi,

our build images jobs are taking too much time to download resources from internet/intranet(so cannot use even mirror registry).

We are looking at sharing cache so that we can save some time during docker builds.

After looking at multiple pages i understand we cannot share /var/lib/docker folder is there any way to share the docker cache?

Thanks in advance.

**Comment by webratz** [comment]
I think this is out of scope for what this plugin does, as it relates more to how ECS stores images.

One strategy that works if you know what images are in use a lot, is to bake them into your ECS optimized AMI
