### ISSUE TITLE
Feature request: Support for multiple labels

### ISSUE THREAD

**Issue by tianx2** [jenkinsci/amazon-ecs-plugin#124]
It would be nice to assign multiple labels to an `ECS agent template` instead of just the one. The use case for this is that I have ECS agents that have the same image but are running in either a different VPC or AWS account. So I would like my `Jenkinsfile` script to support

```groovy
agent {
    label 'java8 && aws-account:some-team && vpc:qa'
}
```

I would also like to request that a `label` parameter be added to the cloud configuration so that it can be inherited by the ecs agent templates. That way I don't have to repeat the label on each ecs agent template that are part of the same ECS cluster/cloud.

Allowing multiple labels allows jobs to be more flexible or more precise in choosing slaves to execute on.

**Comment by jakauppila** [comment]
This would be great to have; is there much refactoring required to enable this?
