### ISSUE TITLE
Plugin is not able to run Task in ECS EC2 unless save configuration thru console 

### ISSUE THREAD

**Issue by satishdg** [jenkinsci/amazon-ecs-plugin#126]
Jenkins is not able to run a task in ECS EC2 until unless I save or apply configuration thru console. We are launching Jenkins thru JCasC v1.27 and using Amazon Elastic Container Service plugin v1.22 (amazon-ecs) and throwing below exception in logs.

Logs before Apply configurations thru Console:
---------------------------------------------------------------------------------------------------------------------------
Aug 22, 2019 10:27:28 AM com.cloudbees.jenkins.plugins.amazonecs.ECSCloud provision
INFO: Asked to provision 1 agent(s) for: Linux
Aug 22, 2019 10:27:28 AM com.cloudbees.jenkins.plugins.amazonecs.ECSCloud provision
INFO: In provisioning : []
Aug 22, 2019 10:27:28 AM com.cloudbees.jenkins.plugins.amazonecs.ECSCloud provision
INFO: Excess workload after pending ECS agents: 1
Aug 22, 2019 10:27:28 AM com.cloudbees.jenkins.plugins.amazonecs.ECSCloud provision
INFO: Will provision ECS Agent Linux, for label: Linux
Aug 22, 2019 10:27:28 AM hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
INFO: Started provisioning ECS Agent Linux from V2-Pipeline with 1 executors. Remaining excess workload: 0
Aug 22, 2019 10:27:38 AM hudson.slaves.NodeProvisioner$2 run
INFO: ECS Agent Linux provisioning successfully completed. We have now 4 computer(s)
Aug 22, 2019 10:27:38 AM com.cloudbees.jenkins.plugins.amazonecs.ECSCloud provision
INFO: Asked to provision 1 agent(s) for: Linux
Aug 22, 2019 10:27:38 AM com.cloudbees.jenkins.plugins.amazonecs.ECSCloud provision
INFO: In provisioning : [V2-Pipeline-f9rnw]
Aug 22, 2019 10:27:38 AM com.cloudbees.jenkins.plugins.amazonecs.ECSCloud provision
INFO: Excess workload after pending ECS agents: 0
Aug 22, 2019 10:27:39 AM com.cloudbees.jenkins.plugins.amazonecs.ECSService registerTemplate
INFO: Match on container definition: true
Aug 22, 2019 10:27:39 AM com.cloudbees.jenkins.plugins.amazonecs.ECSService registerTemplate
INFO: Match on volumes: true
Aug 22, 2019 10:27:39 AM com.cloudbees.jenkins.plugins.amazonecs.ECSService registerTemplate
INFO: Match on task role: true
Aug 22, 2019 10:27:39 AM com.cloudbees.jenkins.plugins.amazonecs.ECSService registerTemplate
INFO: Match on execution role: true
Aug 22, 2019 10:27:39 AM com.cloudbees.jenkins.plugins.amazonecs.ECSService registerTemplate
INFO: Match on network mode: true
Aug 22, 2019 10:27:39 AM com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher runECSTask
INFO: [V2-Pipeline-f9rnw]: Starting agent with task definition arn:aws:ecs:us-west-2:*******:task-definition/V2-Pipeline-npe-v2-pipeline:1}
Aug 22, 2019 10:27:39 AM com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
WARNING: [V2-Pipeline-f9rnw]: Error in provisioning; agent=com.cloudbees.jenkins.plugins.amazonecs.ECSSlave[V2-Pipeline-f9rnw]
com.amazonaws.services.ecs.model.InvalidParameterException: Override argument cannot be null. (Service: AmazonECS; Status Code: 400; Error Code: InvalidParameterException; Request ID: 4a9d3be7-3cbf-4859-935e-51d54ed7133d)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1712)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1367)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1113)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
	at com.amazonaws.services.ecs.AmazonECSClient.doInvoke(AmazonECSClient.java:3934)
	at com.amazonaws.services.ecs.AmazonECSClient.invoke(AmazonECSClient.java:3901)
	at com.amazonaws.services.ecs.AmazonECSClient.invoke(AmazonECSClient.java:3890)
	at com.amazonaws.services.ecs.AmazonECSClient.executeRunTask(AmazonECSClient.java:2795)
	at com.amazonaws.services.ecs.AmazonECSClient.runTask(AmazonECSClient.java:2766)
	at com.cloudbees.jenkins.plugins.amazonecs.ECSService.runEcsTask(ECSService.java:358)
	at com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher.runECSTask(ECSLauncher.java:221)
	at com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher.launch(ECSLauncher.java:109)
	at hudson.slaves.SlaveComputer$1.call(SlaveComputer.java:294)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
--------------------------------------------------------------------------------------------------------------------------------------------------------------
Logs after Apply configurations thru Console:
----------------------------------------------------------------------------------------
Aug 22, 2019 12:17:18 PM com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher runECSTask
INFO: [V2-Pipeline-qq35v]: Starting agent with task definition arn:aws:ecs:us-west-2:********:task-definition/V2-Pipeline-npe-v2-pipeline:1}
Aug 22, 2019 12:17:18 PM com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher runECSTask
INFO: [V2-Pipeline-qq35v]: Agent started with task arn : arn:aws:ecs:us-west-2:********:task/aa3854e0-0d9e-4d48-a4c6-856da9368f66
Aug 22, 2019 12:17:18 PM com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
INFO: [V2-Pipeline-qq35v]: TaskArn: arn:aws:ecs:us-west-2:*******:task/aa3854e0-0d9e-4d48-a4c6-856da9368f66
Aug 22, 2019 12:17:18 PM com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
INFO: [V2-Pipeline-qq35v]: TaskDefinitionArn: arn:aws:ecs:us-west-2:*******:task-definition/V2-Pipeline-npe-v2-pipeline:1
Aug 22, 2019 12:17:18 PM com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
INFO: [V2-Pipeline-qq35v]: ClusterArn: arn:aws:ecs:us-west-2:*******:cluster/npe-v2-pipeline
Aug 22, 2019 12:17:18 PM com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
INFO: [V2-Pipeline-qq35v]: ContainerInstanceArn: arn:aws:ecs:us-west-2:*******:container-instance/8e75e7be-0f0a-41d0-a926-214f87d430e6
Aug 22, 2019 12:17:18 PM com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
INFO: [V2-Pipeline-qq35v]: Waiting for agent to start
Aug 22, 2019 12:17:19 PM com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
INFO: [V2-Pipeline-qq35v]: Waiting for agent to start
Aug 22, 2019 12:17:35 PM com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
INFO: [V2-Pipeline-qq35v]: Agent connected
Aug 22, 2019 12:17:35 PM com.cloudbees.jenkins.plugins.amazonecs.ECSComputer taskAccepted
INFO: [V2-Pipeline-qq35v]: JobName: part of testp_monolith Â» build-pipeline Â» test-monolith Â» v2pipeline_testbranch_3 #16
Aug 22, 2019 12:17:35 PM com.cloudbees.jenkins.plugins.amazonecs.ECSComputer taskAccepted

Can someone please take a look and advice.

thanks,
Satish
![ecs-plugin-config-2](https://user-images.githubusercontent.com/49460699/63543797-7667b980-c4d8-11e9-9944-a3b8302b3737.PNG)
![ecs-plugin-config-1](https://user-images.githubusercontent.com/49460699/63543799-77005000-c4d8-11e9-9b9d-c997656a8361.PNG)

**Comment by webratz** [comment]
Can you share the config xml (snippet) as text before and after the manual safe?

**Comment by satishdg** [comment]
Thanks for quick response!. I have enclosed config.xml before and after manual safe.

[config_xml_after_apply_thru_console.txt](https://github.com/jenkinsci/amazon-ecs-plugin/files/3535751/config_xml_after_apply_thru_console.txt)
[config_xml_before_apply_thru_console.txt](https://github.com/jenkinsci/amazon-ecs-plugin/files/3535752/config_xml_before_apply_thru_console.txt)

**Comment by satishdg** [comment]
The issue is fixed after adding below 2 tags in config.xml hence I am closing the issue.

      <tunnel></tunnel>
      <jenkinsUrl>https://test-poetpipeline.t-mobile.com/</jenkinsUrl>

**Comment by jbentler** [comment]
I was able to resolve this by adding the `jenkins-url` field in my JCasC cloud config. This shouldn't have been needed as the URL is the same as the controller's base but it was being added when saving the cloud after running the JCasC and solving the issue.
`jenkins:
  clouds:
    - ecs:
        cluster: "foo"
        name: "bar"
        jenkinsUrl: "https://${JENKINS_URL}"`
