### ISSUE TITLE
Support "Usage" parameter for default builds on ECS

### ISSUE THREAD

**Issue by dsouzajude** [jenkinsci/amazon-ecs-plugin#127]
Hi, I have a use-case where if i don't provide any label, my builds execute on the master, but instead, i want the builds to be executed by default on ECS slaves. I've seen in some cloud plugins there is this `Usage` parameter (attached) that has two options:
1. Use this node as much as possible (aka Mode: NORMAL)
2. Only build jobs with label expressions matching this node. (aka Mode: EXCLUSIVE)

I believe this plugin works only with option 2, but Is there any way to use option 1 so that my builds don't, by default, execute on the master but rather on ECS slaves? Is this even possible?

Thanks!

<img width="944" alt="aws-ecs-jenkinscli" src="https://user-images.githubusercontent.com/824203/64293927-f2004680-cf6d-11e9-9912-9dff13cca1d9.png">

And thank you for creating a really nice plugin :)

**Comment by webratz** [comment]
As always: glad to review and merge PRs for this :)
