### ISSUE TITLE
Declarative pipelines don't work with any overrides

### ISSUE THREAD

**Issue by StoyanIvanovI** [jenkinsci/amazon-ecs-plugin#128]
I am using the version of the plugin 1.23 with Jenkins 2.176.2.  I have a cloud associated with a template and the plugin starts ECS agents correctly when called with an `agent { label 'ecs-label'}` and also from a freestyle project with using the same label and restrictions. Then I am trying a very simple declarative pipeline:
```groovy
pipeline {
    agent {
        ecs {
            inheritFrom 'ecs-label'
        }
    }

  stages {
    stage('Test') {
        steps {
            sh 'echo hello'
        }
    }
  }
}
```
Which results in the error message
```bash
ERROR: Not allowed to override inheritFrom. Allowed overrides are 
Finished: FAILURE
```
The peculiar part is that this worked correctly with version 1.22 until I created a second cloud in a different region and I have not managed to run an `agent { ecs { } }` block with any configuration since.
I have tried reinstalling the plugin. I upgrade to the latest version - 1.22 - deleted all the clouds and recreated them all resulting in the same error.
I used to get a list of supported allowed overrides, at the moment I only get an empty string for allowed overrides.

**Comment by StoyanIvanovI** [comment]
I was wondering if someone else has similar issues and if it is reproducible as that is a big blocker for my organisation's adoption of the plugin as overriding task roles in a declarative pipeline is our main use case.

**Comment by davidsloan** [comment]
@StoyanIvanovI I have the same issue at the moment.  Did you find a workaround?

**Comment by StoyanIvanovI** [comment]
@davidsloan, sadly, I have not. I was hoping to get a confirmation the issue is not isolated to our Jenkins deployment. Hopefully this will attract a little more attention.

**Comment by StoyanIvanovI** [comment]
So, I have some progress. You have to manually say which values are overridable for each cluster. Under Advanced for each cluster you can find the `Allowed declarative settings`. The description of the filed says
> Settings allowed to be used in the declarative pipeline. Use all for unrestricted use. Always include label, otherwise no agent can be defined. The default is none for security reasons, which fully disables the use of declarative settings.

I will test that next week and will report if that was my problem. This should not be buried in the advanced settings if it is so critical for the plugin's operation.

**Comment by StoyanIvanovI** [comment]
I can confirm that was indeed the problem. Putting `all` or a subset of anything else that can be overridden works. Would have been helpful to be given information or at least to have been pointed at the documentation. I think this needs to be made much clearer in the README.
