### ISSUE TITLE
using ssh slaves instead of jnlp slaves

### ISSUE THREAD

**Issue by rittneje** [jenkinsci/amazon-ecs-plugin#130]
For our use case, the master is not accessible from the internet, so we need to launch agents via ssh as opposed to jnlp. However, I don't see any way of setting this. Is this feature missing?

**Comment by bradq** [comment]
Could you clarify what the process you're proposing looks like? 

Neither the JNLP slaves nor the master require access from the broader Internet to function properly. You can, and indeed should, use RFC 1918 addresses to handle communication between slave and master.

**Comment by rittneje** [comment]
When I use this plugin, the slave images try to connect to the master, and the master waits for them to connect. But that cannot work because of firewall restrictions. (The master is running on a normal local server, not on AWS.) Instead, we need to have the master reach out to the slaves via SSH. In other words, we require the "Launch agent via SSH" functionality from the [SSH slaves plugin](https://wiki.jenkins.io/display/JENKINS/SSH+Slaves+plugin).
