### ISSUE TITLE
taskDefinitionOverride Not working as expected.

### ISSUE THREAD

**Issue by connal-m** [jenkinsci/amazon-ecs-plugin#131]
Hi, 
I am trying to use this plugin to run ECS agents with as little configuration on the jenkins side as possible, ie very little config in the jenkinsfile and no ECS Agent Templates. I can get it to work sort of...

However I find I must always declare `inheritFrom` in my jenkinsfile, or else my build fails once they are completed as they cannot do 'removeDynamicTemplate'. Looking at the code I see https://github.com/jenkinsci/amazon-ecs-plugin/blob/d915d6fa79cdab6c314d1202b52575a90b53b117/src/main/java/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSTaskTemplateStepExecution.java#L179 is the issue.
It is saying to find a template override it must have a value from inheritFrom. This makes sense only to write a nice log, I removed this and changed it to check the value of `getTaskDefinitionOverride()` and it works perfectly for my use case. Am I doing something wrong or should I make PR to fix this? Thanks 🙂

**Comment by conorjduggan** [comment]
Oh great work!! Been hitting this issue myself too.. It'd be great if we could get this merged soon @webratz

**Comment by connal-m** [comment]
Fixed by #132
