### ISSUE TITLE
[Doc] Jenkins wiki sunset

### ISSUE THREAD

**Issue by hauntingEcho** [jenkinsci/amazon-ecs-plugin#142]
Currently the readme forwards users to the Jenkins wiki page.  However, the Jenkins wiki has been converted to read-only mode and is pushing for a migration to documentation-as-code (see both the big red warning on the top of the [wiki page](https://wiki.jenkins.io/display/JENKINS/Amazon+EC2+Container+Service+Plugin) and [this posting](https://jenkins.io/blog/2019/10/21/plugin-docs-on-github/)).  Ideally, the documentation from the wiki should be moved to the readme.

**Comment by markyjackson-taulia** [comment]
Thank you for this

**Comment by webratz** [comment]
moved most of the content in the wiki over to the readme. did not move screenshots as they are all outdated.
also didn't revamp the docs and adding examples, but at least we having the things out of the wiki
