### ISSUE TITLE
[Doc] example mentioned but missing in readme

### ISSUE THREAD

**Issue by hauntingEcho** [jenkinsci/amazon-ecs-plugin#143]
per the readme:

> Declarative agents can be defined like shown below. You can also reuse pre-configured templates and override certain settings using inheritFrom to reference the Label field of the template that you want to use as preconfigured. Only one label is expected to be specified.

however, there's no example shown of configuration without using pre-configured templates and inheritFrom.

**Comment by markyjackson-taulia** [comment]
I can add this
