### ISSUE TITLE
Does ECS plugin support agents connecting directly to tcp port?

### ISSUE THREAD

**Issue by liangming2003** [jenkinsci/amazon-ecs-plugin#147]
https://github.com/jenkinsci/remoting/blob/master/docs/tcpAgent.md#connect-directly-to-tcp-port

**Here is the command in one of my ECS task detail:**

Command | ["-url","http://jenkins-master-alb-1874758640.us-east-1.elb.amazonaws.com:8080/","-tunnel","Jenkins-Master-NLB-1a610ec726b19db5.elb.us-east-1.amazonaws.com:50000","c13783e0173a5a3d21c464aed5be0c45811c5afae08712c24cebb7a786d899ee","ecs-cloud-lnx-r67b0"]

**Here is the command for connecting directly to tcp port.**

Command | ["-direct","Jenkins-Master-NLB-1a610ec726b19db5.elb.us-east-1.amazonaws.com:50000","-instanceIdentity","$JENKINS_INSTANCE_IDENTITY","$JENKINS_SECRET","$JENKINS_AGENT_NAME"]

**Here is the script I used  for agent image entrypoint.**
https://github.com/jenkinsci/docker-jnlp-slave/blob/master/jenkins-agent

If it is supported, how to do it in the plugin settings or in ecs task definition? Thanks.

**Comment by webratz** [comment]
Hey,

as this is a more recent addition I don't think it has been tested before.
You can override the `JVM arguments` in the advanced section to put in the parameter you need possibly.

If you have something working feel free to add a PR to add it to the docs

**Comment by Extracreative** [comment]
@wadatka Has there been any development on this as /tcpslaveagentlistener always returns 401 because I'm using Github oAuth to login to jenkins, so I need the slaves to connect directly to the master.
