### ISSUE TITLE
Question - Do I need to have running EC2 within ECS cluster to start build

### ISSUE THREAD

**Issue by badsector3** [jenkinsci/amazon-ecs-plugin#151]
I am getting following Error:  No Container Instances were found in your cluster
I use EC2 ECS but I don't have any EC2 running in the ECS cluster. I thought the EC2 can be launched dynamically.

**Comment by webratz** [comment]
Not entirely sure about this. Best is to reach out to AWS support for this.

**Comment by badsector3** [comment]
Thanks webratz. Yes you need to have EC2 running in ECS cluster otherwise the container will fail. 

I was more asking about the plugin itself - if the plugin is able to dynamically add EC2 to ECS cluster?
Something similar to [Amazon EC2 plugin](https://plugins.jenkins.io/ec2) where EC2 is started dynamically and terminated after scheduled idle time. 

I am aware of Fargate but this solution in twice as expensive as ECS EC2 especially if you have night builds etc. 
I think it would be good to add such feature to the plugin to keep the cost down.

**Comment by wuillaum** [comment]
The plugin does not launch EC2 instances on your behalf.  I recommend using AWS's auto-scaling groups to accomplish this. Launching EC2 instances as a part of this plugin would not be trivial as CPU/memory resources per label would need to be tracked.

**Comment by badsector3** [comment]
wuillaum AWS ASG (auto-scaling group) does not solve the issue. 
The problem is that you always have to have one EC2 running.

I just configured ASG with desirable and min = 0. That terminated the EC2 within ECS but ECS had not launched new EC2 when there was a new service added by the plugin for build. 

ASG policy configured per memory reservation will do the scaling out/in and can do the memory resource tracking. 

The feature I talk about is to check if there is any EC2 within the configured ECS cluster and to start new EC2 before task definition and container service is added if no EC2 was found.

Configuration of such feature would require to provide EC2 type, tags, security groups, vpc and subnet-id as well as ECS cluster name. All of that must reflect the resources ID on AWS. IAM user with appropriate policy would be required as well.

**Comment by wuillaum** [comment]
From the description of the plugin:
>As a pre-requisite, you must have created an Amazon ECS cluster with associated ECS instances. These instances can be statically associated with the ECS cluster or can be dynamically created with Amazon Auto Scaling.

>The Jenkins Amazon EC2 Container Service plugin will use this ECS cluster and will create automatically the required Task Definition.

I understand the convenience of spinning up 1 EC2 instance if there isn't one already, but this plugin assumes you're fully managing your ECS cluster and its scaling policies on your own.

**Comment by pmoosh** [comment]
AWS has a new feature for ECS:
https://aws.amazon.com/blogs/aws/aws-ecs-cluster-auto-scaling-is-now-generally-available/

"Now because instances are not yet available to run the tasks, the tasks go into a provisioning state, which means they are waiting for capacity to become available. The capacity provider I configured will now scale-out the auto scaling group so that instances start up and join the cluster – at which point the tasks get placed on the instances. This gives a true “scale from zero” capability, which did not previously exist."

**Comment by badsector3** [comment]
Thanks pmoosh. That what I was looking for.
