### ISSUE TITLE
Windows agent run command does not have required options

### ISSUE THREAD

**Issue by dcowan-vestmark** [jenkinsci/amazon-ecs-plugin#155]
The windows docker container expects argument prefixes and the linux agent does not
From the docs: 
Linux agent:
docker run jenkins/jnlp-slave -url http://jenkins-server:port _secret agentname_
Windows agent:
docker run jenkins/jnlp-agent:latest-windows -Url http://jenkins-server:port -Secret _secret_ -Name _agent_name_

Notice that the -Name and -Secret option are prefixed to the values on windows.  This is not passed by the plugin

https://github.com/jenkinsci/amazon-ecs-plugin/blob/402d0239e2ddf612e45c394a4cb86e6fd1cabca6/src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSLauncher.java#L241-L251

**Comment by carpnick** [comment]
I think I am opening a ticket on the windows docker for this.  I dont think they should force all cloud plugins to conform.  They should conform the interface on their side.

**Comment by pavanmr94** [comment]
I have a PR here https://github.com/jenkinsci/amazon-ecs-plugin/pull/202 that adds this feature. Feel free to build on it.

**Comment by pavanmr94** [comment]
Can we get some action on this please?
