### ISSUE TITLE
Fargate spot instance configuration

### ISSUE THREAD

**Issue by dcowan-vestmark** [jenkinsci/amazon-ecs-plugin#156]
I have not found any way to configure fargate spot instances.  I tried disabling fargate in the capabilities in AWS console for the cluster hoping that would fallback to the FARGATE_SPOT configuration but the task still specifies FARGATE and forces that.  It would be nice to allow FARGATE_SPOT to be used.

**Comment by webratz** [comment]
feel free to create a PR to add this option
