### ISSUE TITLE
ECSProvisioningStrategy doesn't consider planned capacity

### ISSUE THREAD

**Issue by asafg6** [jenkinsci/amazon-ecs-plugin#158]
Checked this with version 1.26
Jenkins asks for nodes continuously, reporting wrong excess workload.

ProvisioningStartegy class should use getPlannedCapacitySnapshot() to check if Jenkins has any planned capacity.

I suggest using the  something like this in `apply` method:
```
int excessWorkload = snap.getQueueLength() + state.getPlannedCapacitySnapshot() - snap.getAvailableExecutors() - snap.getConnectingExecutors();
```

**Comment by NorseGaud** [comment]
Bump

**Comment by NorseGaud** [comment]
Bump

**Comment by NorseGaud** [comment]
Bump!!

**Comment by webratz** [comment]
jenkins core now was some more features for that. if someone is up for implementing that in this plugin: https://github.com/jenkinsci/jenkins/pull/4922
