### ISSUE TITLE
Option for Normal mode instead of Exclusive, null labels

### ISSUE THREAD

**Issue by kuhner** [jenkinsci/amazon-ecs-plugin#159]
I'm working on converting an on-prem Jenkins setup to use Amazon ECS. 

It would be a great benefit if I could setup the Cloud so that it runs in "Normal" mode and accepts builds with a null label. Our current on prem Jenkins does this but due to the way this plugin is programmed I will have to go change build pipelines to use a label for more than 40+ repositories.

Is anyone available to make this change?

**Comment by webratz** [comment]
You could do sth like
```groovy
@NonCPS
def call(String label, Closure body) {
    def errorMessage = checkLabel(label)
    if (errorMessage) {
        error errorMessage
    }

    DSL steps = getBinding().getVariable('steps') as DSL
    steps.invokeMethod('node', [label, body] as Object[])
}
```
in a shared library and override `node`
instead of the `checkLabel` function you would just set a default if its empty / null

**Comment by cgrubesol** [comment]
I have this solution implemented and lightly tested. My node.groovy implementation looks like this . . .

`@NonCPS
def call(Closure body) {
    this.call('', body)
}

@NonCPS
def call(String label, Closure body) {
    newLabel = label.trim() ? label.trim() : 'your_default_label'

    println "Custom node implementation using label: $newLabel"
    steps.invokeMethod('node', [newLabel, body] as Object[])
}`

Hope this helps someone.
