### ISSUE TITLE
Reuse fargate tasks

### ISSUE THREAD

**Issue by steveparkerSG** [jenkinsci/amazon-ecs-plugin#163]
I've got the plugin working to run jobs with fargate tasks. However the tasks seem to exit after running a single job. Are there any flags or config I can set to have them sit idle for a while and accept other jobs?

**Comment by webratz** [comment]
works as designed ;) the intention  is that containers are single use to ensure  a fresh and clean environment

**Comment by steveparkerSG** [comment]
I get that, but Fargate tasks have some inherent lag with image pulls. It would be great to have the option to reuse them.

**Comment by chb0github** [comment]
@steveparkerSG - did you manage to get them working using declarative scripts and overrides?

**Comment by chb0github** [comment]
@steveparkerSG - side note about your spin-up time: Use an EC2 cluster

**Comment by webratz** [comment]
#153 is related i guess and might fix it

**Comment by webratz** [comment]
this is released as 1.31 fixed by #153
