### ISSUE TITLE
Support for ECS PlatformVersion

### ISSUE THREAD

**Issue by tst-nstires** [jenkinsci/amazon-ecs-plugin#165]
[Amazon just launched Fargate 1.4](https://aws.amazon.com/about-aws/whats-new/2020/04/aws-fargate-launches-platform-version-14/), which hosts a number of updates that we're looking forward to implementing.

Due to amount of changes, the default "latest" is being held back to v1.3. There's a new parameter with the task launch to specify PlatformVersion, but I'm unable to find anywhere to set this inside of the Jenkins plugin.

https://docs.aws.amazon.com/AmazonECS/latest/developerguide/platform_versions.html

**Comment by rohitagarwal11** [comment]
Can you please help in releasing this in next version @webratz. until then we can't take advantage of this feature.

**Comment by webratz** [comment]
This is currently not a supported parameter. But feel free to create a PR to add this

**Comment by webratz** [comment]
This is an example fo someone adding a parameter. This can be used maybe as starting point https://github.com/jenkinsci/amazon-ecs-plugin/issues/165

**Comment by rohitagarwal11** [comment]
@webratz I made the changes for including this feature. But i am not able to raise the PR due to permission issue:

remote: Permission to jenkinsci/amazon-ecs-plugin.git denied to rohitagarwal11.
fatal: unable to access 'https://github.com/jenkinsci/amazon-ecs-plugin.git/': The requested URL returned error: 403

Can you fix this?

**Comment by webratz** [comment]
you need to create a fork and create the PR from there

**Comment by rohitagarwal11** [comment]
Thanks. Opened the PR: https://github.com/jenkinsci/amazon-ecs-plugin/pull/176
@webratz

**Comment by webratz** [comment]
fixed by #176 which is merged now

**Comment by rohitagarwal11** [comment]
@webratz : When we can expect a new release?

**Comment by webratz** [comment]
i'm just wondering: does a release with just that make sense, without the option to use EFS yet?
or what would be the benefits of Fargate 1.4 that you can already use?

**Comment by tst-nstires** [comment]
1.4 has other improvements. The volume size goes from 4G to 20G, and you can mount EFS/NFS from entrypoint with supported privileged mode in 1.4.

**Comment by rohitagarwal11** [comment]
Also we can use efs support using task definition override option. Once this get released. I will work on adding efs support as well here. @webratz

**Comment by webratz** [comment]
just released 1.34
might take a bit until its shown in the update center

**Comment by tst-nstires** [comment]
Thank you! I'll let you know how it looks on our side.
