### ISSUE TITLE
Requested information for Scripted Pipeline syntax

### ISSUE THREAD

**Issue by jlentink** [jenkinsci/amazon-ecs-plugin#183]
Hello,

I need the information to use theamazon-ecs-plugin in a Scripted Pipeline. 

The syntax generator provides the following code.
```
// This step should not normally be used in your script. Consult the inline help for details.
ecsTaskTemplate(containerUser: '', cpu: 1, executionRole: 'ecsTaskExecutionRole', image: 'jenkins/inbound-agent', inheritFrom: '', label: '', launchType: 'EC2', logDriver: '', name: 'jenkins-agent', networkMode: 'bridge', remoteFSRoot: '/home/jenkins', securityGroups: '', subnets: '', taskDefinitionOverride: '', taskrole: '') {

   // some block
}
```

And the Declarative Pipeline uses the agent syntax that is not available in scripted as far as I'm aware of. Could you please provide the information to complete the setup.

**Comment by markyjackson-taulia** [comment]
Thank you @jlentink 
As discussed on IRC, I I'll look this over tonight

**Comment by jlentink** [comment]
@markyjackson-taulia Thank you so much for spending some time on this.

**Comment by wuillaum** [comment]
I've added some examples that I've used myself to the README in this PR https://github.com/jenkinsci/amazon-ecs-plugin/pull/179/files

**Comment by jlentink** [comment]
Works like a charm. Thanks @markyjackson-taulia

**Comment by markyjackson-taulia** [comment]
Closing now that pr is merged
