### ISSUE TITLE
[Request] Support ECS cluster auto scaling configurations

### ISSUE THREAD

**Issue by bryanburke** [jenkinsci/amazon-ecs-plugin#185]
I know this was already somewhat addressed in #151, however the plugin does not seem to support cluster auto scaling configurations where desired count is zero.

I have an EC2-backed cluster with [cluster auto scaling](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/cluster-auto-scaling.html) configured with a desired count of zero on the underlying Auto Scaling group. If I run a task within that cluster using the [RunTask](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_RunTask.html) API action, the task goes into a PROVISIONING state while ECS tells the ASG an instance is needed. The task then runs once an instance is fully booted and available within the cluster.

With this setup, however, the plugin throws an error if it sees no container instances available in the cluster:

```text
2020-05-20 15:48:03.187+0000 [id=266]	WARNING	c.c.j.p.amazonecs.ECSLauncher#launch: [JenkinsBuild-ec2-generic-fhldc]: Error in provisioning; agent=com.cloudbees.jenkins.plugins.amazonecs.ECSSlave[JenkinsBuild-ec2-generic-fhldc]
com.amazonaws.services.ecs.model.InvalidParameterException: No Container Instances were found in your cluster. (Service: AmazonECS; Status Code: 400; Error Code: InvalidParameterException; Request ID: ...)
```

Would it be possible to support this scenario by detecting the presence of an ECS capacity provider with cluster auto scaling and, instead of failing, waiting for ECS to do its thing?

**Comment by lizhaobibi** [comment]
+1
Probably an easy fix if update [this](https://github.com/jenkinsci/amazon-ecs-plugin/blob/d44930f4a25c0940f67c1adb33a0a0c4a49dde6a/src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSService.java#L384) AWS RunTask API call  to include [withCapacityProviderStrategy](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/ecs/model/RunTaskRequest.html#withCapacityProviderStrategy-com.amazonaws.services.ecs.model.CapacityProviderStrategyItem...-)

**Comment by bryanburke** [comment]
I did some testing and digging into the plugin source code, and I now understand why the plugin does not support ECS managed scaling. Thanks to @lizhaobibi for the hint about the location of the RunTask API call.

The plugin constructs the RunTask API request with the `launchType` parameter [here](https://github.com/jenkinsci/amazon-ecs-plugin/blob/416fd87ab5a2baa4aa368ae448dc306aa240b4b8/src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSService.java#L409). According to the [AWS docs](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_RunTask.html#ECS-RunTask-request-launchType):

> If a `launchType` is specified, the `capacityProviderStrategy` parameter must be omitted.

And again [here](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_RunTask.html#ECS-RunTask-request-capacityProviderStrategy) with a bit more detail:

> If a `capacityProviderStrategy` is specified, the `launchType` parameter must be omitted. If no `capacityProviderStrategy` or `launchType` is specified, the `defaultCapacityProviderStrategy` for the cluster is used.

I tested running tasks in a cluster with managed scaling using the AWS CLI, and I can verify that specifying `launchType` causes an error when no instances are running in the cluster:

```bash
$ aws ecs run-task --cluster CAS-Test --task-definition CAS-Test --launch-type EC2

An error occurred (InvalidParameterException) when calling the RunTask operation: No Container Instances were found in your cluster.
```

When I make the same API call without `launchType`, the task goes into provisioning status and ECS managed scaling triggers scale-out in the ASG to provision capacity so tasks may run.

This behavior of the API explains why the plugin fails to launch tasks with the following error when no instances are running in the cluster:

```text
com.amazonaws.services.ecs.model.InvalidParameterException: No Container Instances were found in your cluster. (Service: AmazonECS; Status Code: 400; Error Code: InvalidParameterException; Request ID: ...)
```

To support ECS managed scaling, I believe the plugin will need either to:

1. Support `capacityProviderStrategy` as an alternative to `launchType` in task templates and use `withCapacityProviderStrategy` like @lizhaobibi mentioned; or
1. Allow the omission of `launchType` in task templates and construct the API request without `withLaunchType` so that the `defaultCapacityProviderStrategy` on the cluster takes over.

AWS has a greatly helpful deep dive into ECS cluster auto scaling here that helped me understand how it actually works: https://aws.amazon.com/blogs/containers/deep-dive-on-amazon-ecs-cluster-auto-scaling/

**Comment by bryanburke** [comment]
I did some more thorough testing with ECS cluster auto scaling. The plugin's current requirement of `launchType` not only breaks configurations where no instances are running in the cluster, it also breaks scale-out entirely when managed scaling is enabled, even with instances running in the cluster already. Here is an example:

**Configuration**

* ASG
  * Desired count: 1
  * Minimum size: 1
  * Maximum size: 5
* Capacity provider
  * Assigned as default capacity provider strategy for cluster.
  * Managed scaling: enabled
    * Minimum scaling step size: 1
    * Maximum scaling step size: 10000
    * Target capacity: 100
  * Managed termination protection: enabled
* Task definition
  * `cpu`: 0.25
  * `memoryReservation`: 512
* Total number of running tasks per instance (t3a.medium): 7

**Desired Behavior**

1. Queue 10 build tasks in Jenkins.
1. Jenkins runs all 10 tasks in ECS.
1. ECS places first 7 on running instance.
1. ECS places remaining 3 in `PROVISIONING` status.
1. ECS managed scaling triggers ASG scale-out to 2 instances.
1. After second instance registers with cluster, ECS places reminaing 3 tasks on it.

**Actual Behavior**

1. Queue 10 build tasks in Jenkins.
1. Jenkins runs 7 tasks in ECS. Remaining 3 stay queued in Jenkins.
1. ECS places first 7 on running instance.
1. After at least 3 of the 7 tasks complete, Jenkins runs remaining 3 in ECS.
1. ECS places remaining 3 on same instance.

As you can see, no cluster auto scaling occurs because Jenkins cannot place tasks for which no instance capacity exists into the `PROVISIONING` status necessary for managed scaling to work.

This issue is similar to #138 (same cause, different effect). In order for the plugin to support cluster auto scaling, it must support capacity providers and do several things:

1. Support `capacityProviderStrategy` as an alternative to `launchType` in task templates and use `withCapacityProviderStrategy` in the `RunTask` API request. This would support configurations where multiple capacity providers are available for use on the cluster.
1. Allow the omission of BOTH `launchType` AND `capacityProviderStrategy` in task templates and construct the API request with NEITHER `withLaunchType` NOR `withCapacityProviderStrategy` so that the `defaultCapacityProviderStrategy` on the cluster takes over. This would support configurations where the default capacity provider strategy on the cluster is always desirable.
1. Offload queuing of ECS build tasks to the cluster when `launchType` is null. This would ensure that Jenkins does not retain builds in its queue when capacity is not available and a capacity provider is handling scaling.

**Comment by chathsuom** [comment]
#211

**Comment by MikeKroell** [comment]
+1

**Comment by saimak** [comment]
+1

**Comment by aroy27** [comment]
+1
