### ISSUE TITLE
Agents fail to provision after restart

### ISSUE THREAD

**Issue by skillingbeck** [jenkinsci/amazon-ecs-plugin#187]
After Jenkins has been restarted, agents fail to provision with the following messages in the logs:
```
May 22, 2020 6:38:55 AM FINE com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher
ECS: Launching agent
May 22, 2020 6:38:55 AM FINE com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher
[ecs-cloud-ecs-main-fmcpc]: Creating Task in cluster null
May 22, 2020 6:38:55 AM WARNING com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
[ecs-cloud-ecs-main-fmcpc]: Error in provisioning; agent=com.cloudbees.jenkins.plugins.amazonecs.ECSSlave[ecs-cloud-ecs-main-fmcpc]
java.lang.NullPointerException
	at com.cloudbees.jenkins.plugins.amazonecs.ECSService.registerTemplate(ECSService.java:150)
	at com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher.getTaskDefinition(ECSLauncher.java:205)
	at com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher.launch(ECSLauncher.java:107)
	at hudson.slaves.SlaveComputer.lambda$_connect$0(SlaveComputer.java:292)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

May 22, 2020 6:38:55 AM FINER com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher
[ecs-cloud-ecs-main-fmcpc]: Removing Jenkins node
```
All builds using ECS agents fail the same way. For context, we use Fargate agents in declarative pipelines, some with overrides on memory, cpu or image

Modifying and saving the agent config resolves the issue temporarily, but it returns as soon as Jenkins is restarted.

- Jenkins v2.222.3
- amazon-ecs-plugin v1.34

~The bit that caught my attention in the logs was `Creating Task in cluster null` - presumably that's not a good sign? Any ideas why the cluster would be null after a restart?~ (this appears to be unrelated, even successful provisioning has this)

This only seems to have begun occurring after we upgraded from v1.26 of the plugin.

**Comment by cl04ker** [comment]
Same problem as above:
```
2020-05-25 11:56:36.692+0000 [id=33]	INFO	hudson.slaves.NodeProvisioner#lambda$update$6: ecs-cloud-Android1-25pdd provisioning successfully completed. We have now 3 computer(s)
2020-05-25 11:56:46.688+0000 [id=38]	INFO	c.c.j.plugins.amazonecs.ECSCloud#provision: Asked to provision 1 agent(s) for: Android1
2020-05-25 11:56:46.689+0000 [id=38]	INFO	c.c.j.plugins.amazonecs.ECSCloud#provision: Will provision ecs-cloud-Android1-40hs7, for label: Android1
2020-05-25 11:56:56.689+0000 [id=81]	WARNING	c.c.j.p.amazonecs.ECSLauncher#launch: [ecs-cloud-Android1-40hs7]: Error in provisioning; agent=com.cloudbees.jenkins.plugins.amazonecs.ECSSlave[ecs-cloud-Android1-40hs7]
java.lang.NullPointerException
	at com.cloudbees.jenkins.plugins.amazonecs.ECSService.registerTemplate(ECSService.java:150)
	at com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher.getTaskDefinition(ECSLauncher.java:205)
	at com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher.launch(ECSLauncher.java:107)
	at hudson.slaves.SlaveComputer.lambda$_connect$0(SlaveComputer.java:292)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

- Jenkins v2.228

- amazon-ecs v1.34

I have tried downgrading to v1.26, I have also tried the workaround listed above to no avail.

As above, this only seems to have begun to occur since upgrading the plugin from v1.26

**Comment by albanf** [comment]
Fix that worked for me: go to https://<jenkins>/configureClouds/ and click Save, then delete the nodes which were being created.

**Comment by skillingbeck** [comment]
> Fix that worked for me: go to https:///configureClouds/ and click Save, then delete the nodes which were being created.

That workaround only works for us until Jenkins is restarted - we shut it down overnight so we have this problem every morning still

**Comment by skillingbeck** [comment]
Some additional detail on curious behaviour: If the first build after a restart does not override the agent settings, then everything seems to be fine thereafter
```
agent { label 'ecs-main' }
```

However if the first build after a restart uses an agent with settings overridden (e.g. image, cpu, memory) then this error will occur until the Cloud configuration is re-saved.
```
agent { 
    ecs {
        inheritFrom 'ecs-main'
        cpu 256
        memory 512
    }
}
```

Any ideas what might cause this/if we are doing something unintended?

**Comment by dimmel82** [comment]
Same with version 1.34, java.lang.NullPointerException after Jenkins restart.
Thanks for the workaround, saved my day!!!

**Comment by mratanji** [comment]
Also seeing the same behavior. At least there is a workaround for now 😃

**Comment by webratz** [comment]
i currently don't have a lot of time to look into this, but thats the diff between the versions.
my assumption is that when using config from older versions it doesn't get a default for that new setting. but i did not check in detail 
https://github.com/jenkinsci/amazon-ecs-plugin/compare/677f0423d1f60f45cbcec35d3498ab14175d93d8...f58f5a2d15e9269a6386e975a46547a5529e85be

**Comment by Bryksin** [comment]
Confirm the similar problem. 
Our plugin version is 1.34, was updated several weeks ago, and we updated settings as it was required. Everything was working, but today I updated other plugins (which were not ECS plugin related) and restarted Jenkins. After the restart, all builds were broken as nodes were not issued with similar exception mentioned above

Thnx to @albanf his solution helped, all I had to go into ECS plugins settings, what for the cluster to be populated automatically, hit apply and save without other changes. 
After that, we got it back online.

So Jenkins restart indeed breaks plugin

**Comment by webratz** [comment]
I don't think its fixed in 1.36 but stacktrace from there would make it easier to reproduce. best would be a testcase :)

**Comment by skillingbeck** [comment]
@webratz We just upgraded to 1.36, the stacktrace from there is the same as @Bryksin posted from 1.34. The same workaround resolves the problem temporarily, but it breaks again after a Jenkins restart.
```
05:54:02  java.lang.NullPointerException
05:54:02  	at com.cloudbees.jenkins.plugins.amazonecs.ECSService.registerTemplate(ECSService.java:193)
05:54:02  	at com.cloudbees.jenkins.plugins.amazonecs.ECSCloud.addDynamicTemplate(ECSCloud.java:414)
05:54:02  	at com.cloudbees.jenkins.plugins.amazonecs.pipeline.ECSTaskTemplateStepExecution.start(ECSTaskTemplateStepExecution.java:95)
05:54:02  	at org.jenkinsci.plugins.workflow.cps.DSL.invokeStep(DSL.java:286)
05:54:02  	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:179)
05:54:02  	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:122)
05:54:02  	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:48)
05:54:02  	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
05:54:02  	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
05:54:02  	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:20)
05:54:02  	at com.cloudbees.jenkins.plugins.amazonecs.pipeline.ECSDeclarativeAgentScript.run(ECSDeclarativeAgentScript.groovy:49)
05:54:02  	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.inDeclarativeAgent(ModelInterpreter.groovy:589)
05:54:02  	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.call(ModelInterpreter.groovy:76)
05:54:02  	at WorkflowScript.run(WorkflowScript:30)
05:54:02  	at ___cps.transform___(Native Method)
05:54:02  	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:86)
05:54:02  	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:113)
05:54:02  	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:83)
05:54:02  	at sun.reflect.GeneratedMethodAccessor260.invoke(Unknown Source)
05:54:02  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
05:54:02  	at java.lang.reflect.Method.invoke(Method.java:498)
05:54:02  	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
05:54:02  	at com.cloudbees.groovy.cps.impl.ClosureBlock.eval(ClosureBlock.java:46)
05:54:02  	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
05:54:02  	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
05:54:02  	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
05:54:02  	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:129)
05:54:02  	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:268)
05:54:02  	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
05:54:02  	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
05:54:02  	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
05:54:02  	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:185)
05:54:02  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:400)
05:54:02  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$400(CpsThreadGroup.java:96)
05:54:02  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:312)
05:54:02  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:276)
05:54:02  	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:67)
05:54:02  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
05:54:02  	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)
05:54:02  	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
05:54:02  	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
05:54:02  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
05:54:02  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
05:54:02  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
05:54:02  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
05:54:02  	at java.lang.Thread.run(Thread.java:748)
05:54:02  Finished: FAILURE

```

**Comment by zswanson** [comment]
We're seeing this same issue, and have noticed this in the Job Config History plugin, to explain the null cluster ID. Apparently something in the plugin resets its config by itself.
<img width="1275" alt="image" src="https://user-images.githubusercontent.com/1272954/85155234-81899400-b226-11ea-8e2b-37bd560661ae.png">

**Comment by wuillaum** [comment]
I'm not sure what's causing this (probably something to do with mismatches with the new config flag), but I believe a more permanent "solution" is logging into your Jenkins and removing the problematic node directories from ${yourInstallPath}/jenkins/nodes

I no longer see `Creating Task in cluster null` when restarting now.

**Comment by tiendungitd** [comment]
> I'm not sure what's causing this (probably something to do with mismatches with the new config flag), but I believe a more permanent "solution" is logging into your Jenkins and removing the problematic node directories from ${yourInstallPath}/jenkins/nodes
> 
> I no longer see `Creating Task in cluster null` when restarting now.

I got the same issue with Jenkins v2.235.1, ecs plugin 1.36. Your solution is not work for me. The workaround below is solved it.


> Fix that worked for me: go to https:///configureClouds/ and click Save, then delete the nodes which were being created.

**Comment by squalou** [comment]
Same issue here

Slightly different stack 

```
Error in provisioning; agent=com.cloudbees.jenkins.plugins.amazonecs.ECSSlave[factory-jenkins-agent-angular-s2wt6]
java.lang.NullPointerException
	at com.cloudbees.jenkins.plugins.amazonecs.ECSService.registerTemplate(ECSService.java:193)
	at com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher.launchECSTask(ECSLauncher.java:148)
	at com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher.launch(ECSLauncher.java:110)
	at hudson.slaves.SlaveComputer.lambda$_connect$0(SlaveComputer.java:296)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by matheusrgomes** [comment]
Also experiencing this issue on 3 of our Jenkins's Dev/QA/Prod.
The fix is to re-save the cloud config.

**Comment by patrickpaul-crew** [comment]
Does anyone know the groovy way of hitting the re-save button? I don't think all clouds need to be saved, just the ECS bits.  I'm thinking something like:
def cloudList = Jenkins.instance.clouds
cloudList.each { it ->
  if (it.name) =~ /.*amazonecs.*/ {
    //do something, maybe with getTemplate/setTemplates
  }
}

If the equivalent of re-save were done as groovy, then it could be thrown in a job and run on a timer, so if Jenkins is ever restarted the job will come along soon enough to fix things like they should be.

**Comment by patrickpaul-crew** [comment]
I found a fix that works for my situation. I can't quite explain why, but I had a hunch ECS was okay and maybe the global cloud configurator (https://jenkins_url/configureClouds) was problematic.  I had 1 EC2 cloud (plugin version 1.51) and 2 ECS clouds (plugin version 1.36) there.

First, I upgraded to 2.252.  After the upgrade, I stopped Jenkins, verified no java process was running, then started Jenkins.  I verified that the problem still existed, the problem that nodes would never start after a Jenkins restart unless I did a re-save on the cloud config.

I made a backup of config.xml before I removed the EC2 cloud and restarted Jenkins.  At this point, there were only 2 ECS clouds in <clouds/>.  After restarting Jenkins, the problem was gone.  I restarted a couple of times, both with service jenkins restart and with the https://jenkins_url/restart link.

I put the EC2 cloud back in place, but I placed it last instead of first in </clouds></clouds>  I started Jenkins with this, and the problem was gone.  I put the original config.xml back in place, restarted Jenkins and the problem appeared again.  I then placed the EC2 cloud 2nd of 3 in <clouds/>, and the problem was gone again.

It looks like this problem appears if you have an EC2 cloud listed first in our cloud config.
It would be awesome if anyone could verify this.

**Comment by jeffj254** [comment]
We've been struggling with this issue but we only have a single ECS cloud and do not use EC2 clouds at all.  At least for us it doesn't seem to be an order-of-operations things.

**Comment by Chris9224** [comment]
For me, it didn't matter if EC2 is listed first or not.
I tried restarting the jenkins service but that didn't work too.
Only way that works so far is by saving the Configure Clouds Page.
Is there a way we can do that via CLI or REST?

**Comment by serpentblade** [comment]
I think I have worked out the fix for at least one variation of this (the NPE on `registerTemplate`). 

It was difficult to debug, as I believe the `ECSCloud` class is serialized; I could never get the debugger to pause on the constructor so concluded it may have been serialized. From my debugging ECSService would always end up with its `Supplier` = `null` after restart.  Thankfully `ECSService` is already lazy-loaded via a call to `ECSCloud.getEcsService()`, so it doesn't actually need to be preserved with ECSCloud.  I switched that field to transient, and have had several successful restarts where I don't encounter this error anymore.

I've created PR #216 if anybody would like to test and verify they see the same success

**Comment by matJC** [comment]
I'm seeing this same issue. Our jenkins deployment doesn't get updated on a regular basis so I'm working through upgrades now, however even with the latest `amazon-ecs` (1.37) plugin, I'm seeing the same issue.

**Comment by serpentblade** [comment]
Hi @matJC,

I have not experienced this issue since upgrading to the latest version of the plugin.  Are you able to find a related error message and stack trace from the logs?  That would assist in identifying if there's another potential bug in the plugin that needs to be tracked down.

**Comment by josemaia** [comment]
Hello,

This just happened to me on version 1.56 of the plugin, on Jenkins 2.249.3, configured by Configuration as Code plugin 1.42. The visible error on the agent logs was
```
ERROR: Unexpected error in launching a slave. This is probably a bug in Jenkins
java.lang.NullPointerException
``` 

In the main Jenkins logs, I can see this:
```
Launching remoting agent (via SSH client process): ssh -o StrictHostKeyChecking=no -i /tmp/ec2_whatever.pem ubuntu@whatever -p 22  java  -jar /tmp/remoting.jar -workDir /tmp
```
Then nothing until I stop it.

Could not extract further logs, because after saving the cloud configs it started working. If in future I can reproduce I will try to get more detailed logs.

**Comment by maryamheni** [comment]
> The fix is to re-save the cloud config.

yarhem bouk bro
