### ISSUE TITLE
Cloud is not an ECS Cloud

### ISSUE THREAD

**Issue by jeremy-page** [jenkinsci/amazon-ecs-plugin#189]
I am trying to use version 1.34 of the Amazon Elastic Container Service (ECS) / Fargate plugin but I am unable to get it to work.

My Amazon EC2 Container Service Cloud settings are:

    Name: aws-claims
    Amazon ECS Credentials: none, using the IAM role
    Amazon ECS Region Name: us-east-1
    ECS Cluster: arn:aws;ecs:us-east-1:XXXXXX:cluster/jenkins-slave

When I run the task it says
> Still waiting to schedule task All nodes of label ‘sbt-test-29-7zv2j’ are offline

I can see a task definition that matches this label in ECS but no container is ever spun up.

My Jenkinsfile: 

    pipeline {
    agent none

    stages {
        stage('Test') {
          agent {
                ecs {
                   cloud 'aws-claims'
                   launchType 'FARGATE'
                   image 'jenkinsci/inbound-agent'
                   memory 2048
                   cpu 1024
                   taskrole 'arn:aws:iam::XXXXXXX:role/jenkins-instance-role'
                   executionRole 'arn:aws:iam::XXXXX:role/ecsTaskExecutionRole'
                   assignPublicIp false
                }
            }
 
           steps {
                sh 'env'
            }
        }
    }
    }

**Comment by jeremy-page** [comment]
The documents say "Note: You have to configure list of settings to be allowed in the declarative pipeline first (see the Allowed Overrides setting). They are disabled by default for security reasons, to avoid non-privileged users to suddenly be able to change certain settings." do I need to do this? I do not see an option to change these settings in the UI (although I have seen old references to it).

**Comment by jeremy-page** [comment]
It looks like this plugin and the [Amazon ECS Scalable](https://plugins.jenkins.io/scalable-amazon-ecs/) plugin have a conflict. Removing the other plugin now gives me the option to set overrides etc.

**Comment by rmsys** [comment]
I receive this all the time **'Still waiting to schedule task All nodes of label ‘xxx-7zv2j’ are offline'**

I don´t know what happens
