### ISSUE TITLE
ECS Plugin Hangs

### ISSUE THREAD

**Issue by fourgates** [jenkinsci/amazon-ecs-plugin#191]
I would like to create a new task revision name "qa-app-api" and update an ECS service name "app-api" in a cluster named "qa" with the new revision. When I run the job, Jenkins incorrectly creates a Task Definition "qa-" (it should have created a new revision for "qa-app-api") which seems to be a truncation of what I want. Jenkins then hangs...

```
[Pipeline] Start of Pipeline
[Pipeline] stage (hide)
[Pipeline] { (Test)
[Pipeline] ecsTaskTemplate
[Pipeline] {
[Pipeline] node
Still waiting to schedule task
‘Jenkins’ doesn’t have label ‘deploy-be-481-5wgz2’
```

Here is my pipeline file:
```
pipeline {
  agent none

  stages {
    stage('Test') {
        agent {
            ecs {
                inheritFrom 'qa-app-api'
                cpu 1024
                memory 2048
            }
        }
        steps {
            sh 'echo hello'
        }
    }
  }
}
```

I attached my configuration and I tired all the examples used on the README.

I am unclear on how this configuration is supposed to work. The setup starts with selecting a cluster that gets pre-populated for me once I added my credentials, so i know that works. then the rest of the configuration seems to be setting up a task definition template, I am familiar with pushing the json version of this via the aws cli. The part that confuses me is how does this template gets mapped to a service? Once the Task Definition is created how does this plugin know what service to update with the new definition? Is this outside the scope of this plugin?

<img width="1817" alt="Screen Shot 2020-06-01 at 6 59 53 PM" src="https://user-images.githubusercontent.com/2994572/83462858-4ae80700-a43a-11ea-81bf-fbfa2894dfce.png">

**Comment by jeremy-page** [comment]
I don't think it's using a service, it's creating a single use task based on the TD you define.

If you try and run a job that matches this label does it try to spin up an agent? I had to take most of the stuff out of the "ECS agent templates" and explicitly add it via my pipeline. Still not quite 100% since I'm using websockets and I think I need to update the base container to understand that - hopefully Jenkins will allow it. But this should get you logging etc.

```
pipeline {
    agent none

    stages {
        stage('Test') {
          agent {
                ecs {
                   cloud 'aws-claims'
                   launchType 'FARGATE'
                   image '0u812.dkr.ecr.us-east-1.amazonaws.com/tools/qppcs/jenkins-slaves:test'
                   memory 2048
                   cpu 1024
                   taskrole 'arn:aws:iam::0u812:role/jenkins-instance-role-automation'
                   executionRole 'arn:aws:iam::0u812:role/jenkins-instance-role-automation'
                   assignPublicIp false
                   subnets ('subnet-1')
                   securityGroups('sg-1,sg-2,sg-3')
                   logDriver 'awslogs'
                   logDriverOptions([[name: 'awslogs-group', value:'jenkins'], [name: 'awslogs-region', value: 'us-east-1'], [name: 'awslogs-stream-prefix', value:'test']])
                   environments([[name: 'JENKINS_WEB_SOCKET', value:'TRUE'],[name: 'JENKINS_URL', value: 'http://jenkins.company.internal/']])
                }
            }
 
           steps {
                sh 'env'
            }
        }
    }
}
```
