### ISSUE TITLE
Support WebSocket connections

### ISSUE THREAD

**Issue by pgardnerjr** [jenkinsci/amazon-ecs-plugin#197]
https://github.com/jenkinsci/jep/blob/master/jep/222/README.adoc

WebSocket support for agents appears to be supported in the latest LTS. The Kubernetes plugin appears to have support as well as of this PR: https://github.com/jenkinsci/kubernetes-plugin/pull/661/files

Is there a chance an option can be added to the ECS Cloud configuration in Jenkins to enable agent connections via WebSocket?

**Comment by eestolano** [comment]
@pgardnerjr I just figured out how to do this.

In the ECS plugin config, you can add environment variables for the container in  "ECS agents templates" -> "Advanced..." -> "Environments". If you set `JENKINS_WEB_SOCKET` to `true`, that will enable websocket connections.

(I found the environment variable in the documentation for the agent container image that the plugin uses: https://hub.docker.com/r/jenkins/inbound-agent/)
