### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by webratz** [jenkinsci/amazon-ecs-plugin#200]
Hey,

this is to give a quick status update on what is up with this plugin and its maintenance:

I've been working on this plugin for a while, mostly due to the fact its used within the setup of my employer and we needed to make some fixes. I'm not having a Java background, so its mostly smaller fixes or getting something just to work.
So most of the time i just try to merge incoming PRs if they don't look horribly wrong.

I'm moving away further from this topic within my company, so the time I can dedicate to this plugin is even less.

In that sense: if there are people that are willing to keep the project healthy and drive it, please reach out to me.

Also see https://www.jenkins.io/doc/developer/plugin-governance/adopt-a-plugin/

**Comment by markyjackson-taulia** [comment]
I think I also have access to handle and will take over @webratz

**Comment by pgarbe** [comment]
It's probably a good time to officially kick me out too.

**Comment by serpentblade** [comment]
@webratz,
I'd be interested in taking over support for this plugin.  I've reached out to the jenkins dev mailing list, and would be interested in discussing with you further the requirements for the role.

**Comment by webratz** [comment]
> @webratz,
> I'd be interested in taking over support for this plugin. I've reached out to the jenkins dev mailing list, and would be interested in discussing with you further the requirements for the role.

didn't see anything on the mailing lists. feel free to reach out there to gain access

**Comment by jayeshmurli** [comment]
@webratz I would also like to contribute to maintain this plugin. This plugin is extensively being used by my employer and I would like to help it keep up-to-date. Could you please grant me the permissions for it.

**Comment by jeremymcgee73** [comment]
@jayeshmurli I believe you need to email the mailing list. [Here](https://www.jenkins.io/doc/developer/plugin-governance/adopt-a-plugin/) is the link!

**Comment by jayeshmurli** [comment]
> @jayeshmurli I believe you need to email the mailing list. [Here](https://www.jenkins.io/doc/developer/plugin-governance/adopt-a-plugin/) is the link!

thanks!

**Comment by jayeshmurli** [comment]
> @jayeshmurli I believe you need to email the mailing list. [Here](https://www.jenkins.io/doc/developer/plugin-governance/adopt-a-plugin/) is the link!

somehow my email to the mailing group is never delivered to the queue. I get a bounce back email stating I dont have permissions to send email to the specified group. Am I missing something here ? 🤔

**Comment by jayeshmurli** [comment]
@jeremymcgee73 @webratz I am interested in supporting this plugin. I have tried sending out an email to the Jenkins Dev Email list, but the email delivery does not succeed. Can someone let me know if I am doing something wrong here ?

**Comment by webratz** [comment]
Hey, i think you need to join the mailinglist first. It also works via a web interface at https://groups.google.com/g/jenkinsci-dev

**Comment by oleg-nenashev** [comment]
FTR https://groups.google.com/g/jenkinsci-dev/c/z0Ia_aMsrwc/m/zkqWfIDeAgAJ for the adoption request

P.S: Thanks a lot to @webratz for maintaining this plugin, and for properly announcing it adoption! Great to see that others can step up and keep evolving this plugin.

**Comment by FnTm** [comment]
@oleg-nenashev I'm not sure who actually processes the maintainer addition requests, but would you think there'd be any way in moving the process in the aforementioned Google Groups thread along?
The Stalebot in this Repo is closing valid feature requests and PRs left and right. We're depending quite heavily on this plugin for our Jenkins setup and would really have wanted to use some of the additions those PR's would have given us.

**Comment by webratz** [comment]
let's keep this open

**Comment by carlosrodf** [comment]
I'm also interested in maintaining this plugin but the email i sent to the dev mailing list is not being delivered.
if someone knows please let me know how to proceed :+1:

**Comment by pgarbe** [comment]
@carlosrodf as far as I know the permissions are managed here: https://github.com/jenkins-infra/repository-permissions-updater/blob/master/permissions/plugin-amazon-ecs.yml 
Maybe it helps if you send them a pull request.

**Comment by gowthamshankar99** [comment]
I m also interested in maintaining this plugin. not sure how to proceed .

**Comment by Stericson** [comment]
@webratz Hello, I'm also interested in adopting / helping to maintain this plugin. I've already submitted a request for Maintainer access and will submit a PR to the permissions repository shortly.

**Comment by webratz** [comment]
> @webratz Hello, I'm also interested in adopting / helping to maintain this plugin. I've already submitted a request for Maintainer access and will submit a PR to the permissions repository shortly.

i guess all done at https://github.com/jenkins-infra/repository-permissions-updater/pull/2312 or anything missing?

**Comment by Stericson** [comment]
Should be once someone approves and merges it. I also assume they'd grant the Github Repo permissions.

Thanks for signing off on the request and for building such a useful plugin 👍

**Comment by neirbowj** [comment]
Multiple people have expressed interest in adopting this plugin, and reported problems following the published process of engaging on the mailing list. After roughly a year and a half, it seems like maybe the established process needs some attention and adjustment before it will achieve the desired result. I haven't found a way to escalate. Is there a next-step in the process that I am missing?

**Comment by Stericson** [comment]
@neirbowj I followed this process -- https://www.jenkins.io/doc/developer/plugin-governance/adopt-a-plugin/ 

It was pretty straightforward. I was added as a maintainer and I've done a few releases since then. A number of folks on this issue also went through this process and also became maintainers at some point. 

My PR [here](https://github.com/jenkins-infra/repository-permissions-updater/pull/2312) has quite a bit of information related to my request if it helps.

**Comment by ugurkany** [comment]
Hey Guys, I would like to remove the adoption status of the plugin if it is okay for you. I will remove it this Saturday if there is no objection. Also, @webratz  Thank you for maintaining this plugin. @Stericson is actively maintaining this plugin too. I believe we can take care of this together.
