### ISSUE TITLE
I'm trying to get the ecs plugin working, I'm getting an aws endpoing error

### ISSUE THREAD

**Issue by sean-abbott** [jenkinsci/amazon-ecs-plugin#206]
Was experimenting with replacing our teamcity with jenkins, but as I try to set up fargate for jenkins, I'm getting this error in the logs:
```

  | 2020-07-20T19:53:52.215-04:00 | 2020-07-20  23:53:52.214+0000 [id=112]	INFO	 c.c.j.p.a.ECSCloud$DescriptorImpl#doFillClusterItems: Exception  searching clusters for credentials=, regionName=
-- | -- | --
 java.lang.IllegalArgumentException: Request endpoint must have a valid hostname, but it did not: https://ecs..amazonaws.com

2020-07-20T19:53:52.215-04:00 | at com.amazonaws.auth.AWS4Signer.addHostHeader(AWS4Signer.java:548)
-- | --

 ```

I did add the permission after I started the jenkins server; are these cached by jenkins, perhaps? Or is there actually an issue with the plugin?

**Comment by jveldboom** [comment]
I'm not sure where you're running this from but based on the ECS endpoint (`https://ecs..amazonaws.com`) in your logs, it looks like the region is not set. The endpoint should look something like this `https://ecs.us-east-1.amazonaws.com`

**Comment by sean-abbott** [comment]
Ah, yeah, sorry, I figured it out later. User error. There was a different us east 1 (gov? some kind of restricted? I'm not sure) at the top of the list, and I had that selected, not the correct one. My bad!
