### ISSUE TITLE
Use tags in Task Definition

### ISSUE THREAD

**Issue by qibint** [jenkinsci/amazon-ecs-plugin#209]
Is there any support to create tags in Task Definition based on the Agent Templates configuration? We'd like to have some tags info added to each of the task revisions. Thanks.

**Comment by bradq** [comment]
There currently is not. I'd love this as well for analytics (memory in particular), since the unique name isn't reliably helpful, but unfortunately lack the time to give to a PR.

**Comment by qibint** [comment]
@bradq It seems like there is an existing PR in here https://github.com/jenkinsci/amazon-ecs-plugin/pull/208 to solve this.

**Comment by bradq** [comment]
Ah, thanks! Meant to point that out to you (going back through my email FILO). The way I read the change, however, it doesn't really cover my use case or fit my understanding of yours. That'll propagate tags from the task definitions, but the task definitions are themselves created by the plugin and there remains no interface for tagging them that I'm aware of unless you're overriding it at the definition. 

My desired implementation is probably too custom/dynamic to be baked into the primary anyhow. I was specifically interested in tracking Jenkins job name, number, etc. The plugin does provide `NODE_LABELS`, so there's some hope that I can simply manually do requested tagging as part of job initialization.

**Comment by qibint** [comment]
Ok, Ic. Still need some work in this PR. Found entries can be added via ECSTaskTemplateStep/[config.jelly](https://github.com/jenkinsci/amazon-ecs-plugin/blob/master/src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSTaskTemplateStep/config.jelly). You probably need to call aws ecs api directly to make those Jenkins metadata happen.

**Comment by lunaticare** [comment]
@qibint is it possible to merge #208 as a workaround now? It would be super helpful for those who use task definitions.
