### ISSUE TITLE
Unable to specify customWorkspace with declarative agent definition.

### ISSUE THREAD

**Issue by AntonyRileyAtVerto** [jenkinsci/amazon-ecs-plugin#212]
I suspect I'm probably missing something, but essentially I'm trying to do something like this:

```groovy
pipeline {
    agent {
        ecs {
            customWorkspace "${java.util.UUID.randomUUID()}"
            inheritFrom 'linux2'
            memory 2048
        }
    }
...
```

We're using multibranch pipeline and the default workspace names have this horrible habit of causing build failures, I can't seem to find a way to set customWorkspace unless you use node {} with a label, which prohibits declaratively setting the memory.

**Comment by ibalosh** [comment]
I am seeing the same issue, is there a workaround for this?
