### ISSUE TITLE
Feature Request: Check EC2 instance state for termination before scheduling new build agent

### ISSUE THREAD

**Issue by Bryksin** [jenkinsci/amazon-ecs-plugin#213]
Hi

We are heavily using this plugin with our Spot Fleet, as you know Spot Instances can be withdrawn by AWS with 2 min notification. We noticed that ECS plugin sometimes schedule new ECS Agent on such instance which was already scheduled for termination, which leads to building progress termination in mid-way through.
Also, our Spot Fleet has autoscaling action, and if we fall into Scale Down action, it also marks instance for termination, but this process is not instant, so ECS plugin sometimes manages to run next build on such instance which was already marked for termination. 

Would be nice if this plugin can check instance metadata for its state, and not schedule a new job on instances which are already scheduled for termination

**Comment by wuillaum** [comment]
As far as I know this isn't in the scope of the ECS plugin to handle, as the plugin does not determine where tasks are started. See https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-placement-strategies.html

Whatever mechanism is marking the instances for termination should also be [marking the container instance as DRAINING](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/container-instance-draining.html) as this will prevent jobs (tasks) from being assigned to said instances.

**Comment by carpnick** [comment]
@Bryksin - We handled this by adding an ASG ScaleIn LifeCycle Scale In.  I have not worked with Spot Fleet, but I assume there is an event you can hook up to.  When you are notified, fire off to lambda to set the instance to draining and you should be good to go.
