### ISSUE TITLE
Multiple cluster, only the first occurrance of a label executes

### ISSUE THREAD

**Issue by statsperformjanos** [jenkinsci/amazon-ecs-plugin#215]
**The problem:**
- Given `Cluster1` and `Cluster2`
- and ECS agent with label `Foo` is created in `Cluster1`
- and ECS agent with label  `Foo Bar` is created in `Cluster2`
- Then when `Job1` is created with label requirement of `Foo`, and `Cluster1` has no resources left to run it, it is not delegated to `Cluster2`, even if it is idle. `Job1` is in pending state until `Cluster1` has enough free capacity again.

**Expected:**
- `Cluster2` executes the job.
- Bonus: the Cluster with less load picks up the job.

**Comment by wuillaum** [comment]
I'm curious to know if this is even possible. As far as I'm aware each cluster is its own "cloud" and is not aware of other clouds in the system. It's up to Jenkins to figure out which resources can provision a label, and for Clouds it does so via [this method](https://javadoc.jenkins-ci.org/hudson/slaves/Cloud.html#canProvision-hudson.model.Label-) implemented here https://github.com/jenkinsci/amazon-ecs-plugin/blob/5032955fe0650973056fbf30498ed57946308b29/src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSCloud.java#L193

Jenkins simply loops through every resource in the system to see if they can provision for a given label, so the first Cloud will win in this case. Once that cloud wins Jenkins will ask the cloud to provision the label, but if it errors I believe Jenkins will simply loop through the clouds again and the process will repeat.
