### ISSUE TITLE
ECS plugin support cross account 

### ISSUE THREAD

**Issue by pmprasad** [jenkinsci/amazon-ecs-plugin#220]
Hi,

  We have a correct setup of Jenkins running in on AWS account A with ECS plugin installed. We have another AWS account B where 
ECS cluster is deployed with right cross role access, but still the cluster is not able to list from Jenkins server. 

  Does ECS plugin support AWS cross account, If yes please share us the any blog which talk on it.

**Comment by tkgregory** [comment]
Hi @pmprasad 

FYI I'm working on a solution at the moment to allow this plugin to assume a role which could be in another AWS account. The implementation will roughly follow what's described in #103 

![image](https://user-images.githubusercontent.com/5338022/97113878-1163b100-16e5-11eb-87cc-e2de8bd7abdc.png)

Is this what you were thinking?

**Comment by pmprasad** [comment]
Yes, I was looking for cross account assume role. Please instruct me from were do I need to download the latest Jenkins ECS plugin where this  #222 is fixed.

**Comment by lukaszciechanowicz** [comment]
Hey @pmprasad. Did you manage to get it sorted? I have stuck with exact the same issue. Thanks in advance.
