### ISSUE TITLE
Provide ability to specify minimum amount of agents

### ISSUE THREAD

**Issue by MikeKroell** [jenkinsci/amazon-ecs-plugin#221]
The issue I'd like to raise here is to specify the minimum amount of available agents on the plugin. I would believe the best place for this would be on the ECS agent template. For our particular setup, we have to use EC2 ECS to be able to use docker in docker to build and push docker images. We leave one instance online at all times for rapid job start but would like the ability to have one agent online at all times to make full use of this instance that is on all the time. This would further reduce the job launching time by 30 seconds - 1 minute.

**Comment by bradq** [comment]
Hey @MikeKroell 2 quick ideas for you:

* Does #153 fit your needs, or is there some subtlety there where "reusing" the agent (rather than keeping a fresh one) causes issues and a new one is required? 
* If you're using this plugin + EC2/ECS I _suspect_ that a 30s-1m launch time could benefit from some attention. Are you seeing that delay before an ECS task is spawned (e.g. it takes 30s for Jenkins to understand that it needs to spawn an agent), or after? For the former, there's a [series of Jenkins options]() that should help in the README. The latter can be a tad more tricky, but I've had good success in setting ECS options to not pull the container anew on each run, instead opting to do so on a schedule. We're launching a lot of jobs, with scheduling delay typically in the 1-2s range, and median job start time of <5s with caching enabled.

**Comment by MikeKroell** [comment]
Hi @bradq,

Thanks for the references. We are using the options in 153, and this works well after the first agent launch. We have them stick around for 90 minutes after the last job was finished. I'd like to add an additional option of saying "keep this many running" which the options in 153 and this option would work in tandem - keep 1 running, any scale out after 1 would use the options in 153.
For the second bullet, I'll time it further, I believe it may be shorter, but trying to avoid that initial spin up for the first job submitted. We have the ECS options echoed in userdata to do updates right now, which pulls on every launch (we have been making changes as this is our first deployment). In the logs, we see no agent available, then it shortly after lists the agent available after it spins up. Our biggest issues right now if the ECS provider for additional scale-out, It doesn't allow Jenkins to submit tasks into a provisioning state, while the ASG scales. As well as the warmup timer is not configurable (so one instance spins up, the next wont spin up for five minutes) but that is out of scope for the particular request.

In the end, we are trying to shave off as much time as possible, as we are working to have developers us Jenkins solely for building docker containers instead of local builds and pushes to ECR.

**Comment by MikeKroell** [comment]
With a single EC2 instance already running, and submitting one build, Here is my log:

`ct 20, 2020 4:59:36 PM FINE com.cloudbees.jenkins.plugins.amazonecs.ECSProvisioningStrategy
Received StrategyState{label=default-agent, snapshot=LoadStatisticsSnapshot{definedExecutors=0, onlineExecutors=0, connectingExecutors=0, busyExecutors=0, idleExecutors=0, availableExecutors=0, queueLength=1}, plannedCapacitySnapshot=0, additionalPlannedCapacity=1}
Oct 20, 2020 4:59:36 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSCloud provision
Asked to provision 1 agent(s) for: default-agent
Oct 20, 2020 4:59:36 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSCloud provision
Will provision DevOps-default-agent-w25cx, for label: default-agent
Oct 20, 2020 4:59:36 PM FINE com.cloudbees.jenkins.plugins.amazonecs.ECSProvisioningStrategy
Started provisioning DevOps-default-agent-w25cx from DevOps with 1 executors. Remaining excess workload: 0
Oct 20, 2020 4:59:46 PM FINE com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher
ECS: Launching agent
Oct 20, 2020 4:59:46 PM FINE com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher
[DevOps-default-agent-w25cx]: Creating Task in cluster null
Oct 20, 2020 4:59:46 PM FINE com.cloudbees.jenkins.plugins.amazonecs.ECSProvisioningStrategy
Received StrategyState{label=default-agent, snapshot=LoadStatisticsSnapshot{definedExecutors=1, onlineExecutors=0, connectingExecutors=1, busyExecutors=0, idleExecutors=0, availableExecutors=0, queueLength=1}, plannedCapacitySnapshot=0, additionalPlannedCapacity=0}
Oct 20, 2020 4:59:46 PM FINE com.cloudbees.jenkins.plugins.amazonecs.ECSCloud
Selected Region: us-east-1
Oct 20, 2020 4:59:47 PM FINE com.cloudbees.jenkins.plugins.amazonecs.ECSCloud
Found task definition override: arn:aws:ecs:us-east-1:456872738803:task-definition/jenkins-test--jenkins-agent:8
Oct 20, 2020 4:59:47 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher runECSTask
[DevOps-default-agent-w25cx]: Starting agent with task definition arn:aws:ecs:us-east-1:456872738803:task-definition/jenkins-test--jenkins-agent:8}
Oct 20, 2020 4:59:47 PM FINE com.cloudbees.jenkins.plugins.amazonecs.ECSCloud
Selected Region: us-east-1
Oct 20, 2020 4:59:47 PM FINE com.cloudbees.jenkins.plugins.amazonecs.ECSCloud
Found container definition with 1 container(s). Assuming first container is the Jenkins agent: jenkins-agent
Oct 20, 2020 4:59:47 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher runECSTask
[DevOps-default-agent-w25cx]: Agent started with task arn : arn:aws:ecs:us-east-1:456872738803:task/jenkins-test-agents/f034a1c75dfe412ba0bae7874b79abb1
Oct 20, 2020 4:59:47 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launchECSTask
[DevOps-default-agent-w25cx]: TaskArn: arn:aws:ecs:us-east-1:456872738803:task/jenkins-test-agents/f034a1c75dfe412ba0bae7874b79abb1
Oct 20, 2020 4:59:47 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launchECSTask
[DevOps-default-agent-w25cx]: TaskDefinitionArn: arn:aws:ecs:us-east-1:456872738803:task-definition/jenkins-test--jenkins-agent:8
Oct 20, 2020 4:59:47 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launchECSTask
[DevOps-default-agent-w25cx]: ClusterArn: arn:aws:ecs:us-east-1:456872738803:cluster/jenkins-test-agents
Oct 20, 2020 4:59:47 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launchECSTask
[DevOps-default-agent-w25cx]: ContainerInstanceArn: arn:aws:ecs:us-east-1:456872738803:container-instance/jenkins-test-agents/f763576cf1e34bd99d3b20d4fdb8efcb
Oct 20, 2020 4:59:47 PM FINE com.cloudbees.jenkins.plugins.amazonecs.ECSCloud
Selected Region: us-east-1
Oct 20, 2020 4:59:56 PM FINE com.cloudbees.jenkins.plugins.amazonecs.ECSProvisioningStrategy
Received StrategyState{label=default-agent, snapshot=LoadStatisticsSnapshot{definedExecutors=1, onlineExecutors=0, connectingExecutors=1, busyExecutors=0, idleExecutors=0, availableExecutors=0, queueLength=1}, plannedCapacitySnapshot=0, additionalPlannedCapacity=0}
Oct 20, 2020 5:00:06 PM FINE com.cloudbees.jenkins.plugins.amazonecs.ECSProvisioningStrategy
Received StrategyState{label=default-agent, snapshot=LoadStatisticsSnapshot{definedExecutors=1, onlineExecutors=0, connectingExecutors=1, busyExecutors=0, idleExecutors=0, availableExecutors=0, queueLength=1}, plannedCapacitySnapshot=0, additionalPlannedCapacity=0}
Oct 20, 2020 5:00:16 PM FINE com.cloudbees.jenkins.plugins.amazonecs.ECSProvisioningStrategy
Received StrategyState{label=default-agent, snapshot=LoadStatisticsSnapshot{definedExecutors=1, onlineExecutors=0, connectingExecutors=1, busyExecutors=0, idleExecutors=0, availableExecutors=0, queueLength=1}, plannedCapacitySnapshot=0, additionalPlannedCapacity=0}
Oct 20, 2020 5:00:26 PM FINE com.cloudbees.jenkins.plugins.amazonecs.ECSProvisioningStrategy
Received StrategyState{label=default-agent, snapshot=LoadStatisticsSnapshot{definedExecutors=1, onlineExecutors=0, connectingExecutors=1, busyExecutors=0, idleExecutors=0, availableExecutors=0, queueLength=1}, plannedCapacitySnapshot=0, additionalPlannedCapacity=0}
Oct 20, 2020 5:00:36 PM FINE com.cloudbees.jenkins.plugins.amazonecs.ECSProvisioningStrategy
Received StrategyState{label=default-agent, snapshot=LoadStatisticsSnapshot{definedExecutors=1, onlineExecutors=0, connectingExecutors=1, busyExecutors=0, idleExecutors=0, availableExecutors=0, queueLength=1}, plannedCapacitySnapshot=0, additionalPlannedCapacity=0}
Oct 20, 2020 5:00:37 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launchECSTask
[DevOps-default-agent-w25cx]: Task started, waiting for agent to become online
Oct 20, 2020 5:00:37 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher waitForAgent
[DevOps-default-agent-w25cx]: Waiting for agent to connect
Oct 20, 2020 5:00:38 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher waitForAgent
[DevOps-default-agent-w25cx]: Waiting for agent to connect
Oct 20, 2020 5:00:39 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher waitForAgent
[DevOps-default-agent-w25cx]: Waiting for agent to connect
Oct 20, 2020 5:00:40 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher waitForAgent
[DevOps-default-agent-w25cx]: Waiting for agent to connect
Oct 20, 2020 5:00:41 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher waitForAgent
[DevOps-default-agent-w25cx]: Waiting for agent to connect
Oct 20, 2020 5:00:42 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher waitForAgent
[DevOps-default-agent-w25cx]: Waiting for agent to connect
Oct 20, 2020 5:00:43 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher waitForAgent
[DevOps-default-agent-w25cx]: Agent connected
Oct 20, 2020 5:00:43 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSComputer taskAccepted
[DevOps-default-agent-w25cx]: JobName: part of jenkins-experimental » CDE-887-test-jira #1
Oct 20, 2020 5:00:43 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSComputer taskAccepted
[DevOps-default-agent-w25cx]: JobUrl: job/jenkins-experimental/job/CDE-887-test-jira/1/
Oct 20, 2020 5:00:43 PM FINE com.cloudbees.jenkins.plugins.amazonecs.ECSComputer
[ECSComputer name: DevOps-default-agent-w25cx agent: com.cloudbees.jenkins.plugins.amazonecs.ECSSlave[DevOps-default-agent-w25cx]]: taskAccepted
Oct 20, 2020 5:01:04 PM FINE com.cloudbees.jenkins.plugins.amazonecs.ECSComputer
[ECSComputer name: DevOps-default-agent-w25cx agent: com.cloudbees.jenkins.plugins.amazonecs.ECSSlave[DevOps-default-agent-w25cx]]: taskCompleted`

**Comment by MikeKroell** [comment]
Bump
