### ISSUE TITLE
Generated Command does not work for Windows Agents

### ISSUE THREAD

**Issue by AndrewCFerrari** [jenkinsci/amazon-ecs-plugin#225]
The command generated by this plugin works for linux agents, but not for windows agents. The command is missing the required "-secret" and "-name" flags given in the [readme for the jenkins/inbound-agent image](https://github.com/jenkinsci/docker-inbound-agent).

### To run a Docker container

Linux agent:
docker run --init jenkins/inbound-agent -url http://jenkins-server:port \<secret\> \<agent name\>

Windows agent:
docker run jenkins/inbound-agent:windowsservercore-1809 -Url http://jenkins-server:port **-Secret** \<secret\> **-Name** \<agent name\>

**Comment by kevit** [comment]
you can fix here    https://github.com/jenkinsci/docker-inbound-agent/blob/498e66cc1779c4cc5587d18c6c4cdad5329a9df2/jenkins-agent.ps1#L27

by adding [Parameter(Position=0)]$Secret and [Parameter(Position=1)]$Name
