### ISSUE TITLE
Support multiple container definitions

### ISSUE THREAD

**Issue by Artemkulish** [jenkinsci/amazon-ecs-plugin#227]
Hello,

Could you please tell me if this plugin can be used to create a task definition with 2 container definitions inside of it? 

I need to start the Jenkins slaves along with the monitoring containers in order to receive the necessary metrics from ecs. 

Unfortunately, I have been unable to find a solution yet.

**Comment by MikeKroell** [comment]
Create the task definition outside of Jenkins and then tell the plugin what task def to use. This is what I do to use EFS.

**Comment by AndyUM357** [comment]
Where in the plugin configuration do you specify a pre-existing task definition to use?  I see where to setup the cluster and I can make ECS Slave Templates that work.  But like Artemkulish above, I would like to specify a task definition that launches multiple containers instead of Jenkins auto-creating one from an ecs slave template.

**Comment by MikeKroell** [comment]
![image](https://user-images.githubusercontent.com/48728771/114553407-9b6fe980-9c33-11eb-94d7-1b3b75308dc6.png)

**Comment by AndyUM357** [comment]
That is pretty wild.  I don't see those lines at all in the configuration UI.  I've tried both v1.37 and 1.38-SNAPSHOT of the plugin.  My Jenkins is v2.263.4.  Any idea what would be suppressing those lines?  
![image](https://user-images.githubusercontent.com/10834485/114604774-52d22380-9c67-11eb-88bb-d09f6afed13b.png)

**Comment by AndyUM357** [comment]
Bah, I figured it out.  It looks like another plugin was interfering -- thanks for the help

**Comment by andreas-doppelhofer** [comment]
Is it somehow possible having a sidecar jenkins/inbound-agent container running besides a second container which should execute the jenkins build steps? I created a Task definition in AWS manually having a jnlp and a second container alpine running but i'm not able to specify the alpine container in my Jenkinsfile.
![image](https://user-images.githubusercontent.com/43139367/115530778-5fbccb80-a294-11eb-887c-03aae83f808f.png)
How can i access/set the container name in Jenkinsfile to execute the build steps in alpine container?
![image](https://user-images.githubusercontent.com/43139367/115532342-fb9b0700-a295-11eb-8ffc-6f57165e6794.png)
Containers are getting created in AWS ECS and are RUNNING and after a short time they are STOPPED and pipeline still waiting for labels 
`All nodes of label ‘myecssidecare-10-blrwr’ are offline`

Is this somehow possible like in https://github.com/jenkinsci/kubernetes-plugin

**Comment by gokhanoner** [comment]
@andreas-doppelhofer no. You need to create your own container using `jenkins-agent` docker image for different use cases/libraries & use that image instead. Side card containers can only be used to run additional resources, like DB, Selenium etc.

example, I'm using below as Jenkins agent to build my Angular app
```
ARG nodeVersion=12

FROM jenkins/inbound-agent:latest AS staging

FROM node:${nodeVersion}-buster-slim

ARG npmPackages
ARG user=jenkins

ENV TZ=America/Los_Angeles

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && rm /etc/timezone && echo $TZ > /etc/timezone

RUN apt-get update && \
    mkdir /usr/share/man/man1/ && \
    apt-get -y --no-install-recommends install ca-certificates git git-lfs openssh-client openssl procps wget apt-transport-https gnupg && \
    wget -qO - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | apt-key add - && \
    echo "deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb buster main" | tee /etc/apt/sources.list.d/adoptopenjdk.list && \
    apt-get update && \
    apt-get -y --no-install-recommends install adoptopenjdk-8-hotspot && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN groupadd -g 9000 jenkins && \
    useradd -c "Jenkins user" -d /home/jenkins -u 9000 -g 9000 -m jenkins

COPY --from=staging --chown=jenkins /usr/local/bin/jenkins-agent /usr/local/bin/jenkins-agent
COPY --from=staging --chown=jenkins /usr/share/jenkins /usr/share/jenkins
RUN chmod +x /usr/local/bin/jenkins-agent && \
    ln -s /usr/local/bin/jenkins-agent /usr/local/bin/jenkins-slave

USER jenkins
ENTRYPOINT ["jenkins-agent"]
```

and this one for Python
```
ARG pythonVersion=3.6

FROM jenkins/inbound-agent:latest AS staging

FROM python:${pythonVersion}-slim

ARG user=jenkins

ENV TZ=America/Los_Angeles

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && rm /etc/timezone && echo $TZ > /etc/timezone

RUN apt-get update && \
    mkdir /usr/share/man/man1/ && \
    apt-get -y --no-install-recommends install git git-lfs openssh-client openssl procps wget apt-transport-https gnupg && \
    wget -qO - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | apt-key add - && \
    echo "deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb buster main" | tee /etc/apt/sources.list.d/adoptopenjdk.list && \
    apt-get update && \
    apt-get -y --no-install-recommends install adoptopenjdk-8-hotspot && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN groupadd -g 1000 jenkins && \
    useradd -c "Jenkins user" -d /home/jenkins -u 1000 -g 1000 -m jenkins

COPY --from=staging --chown=jenkins /usr/local/bin/jenkins-agent /usr/local/bin/jenkins-agent
COPY --from=staging --chown=jenkins /usr/share/jenkins /usr/share/jenkins
RUN chmod +x /usr/local/bin/jenkins-agent && \
    ln -s /usr/local/bin/jenkins-agent /usr/local/bin/jenkins-slave

USER jenkins
ENTRYPOINT ["jenkins-agent"]
```
