### ISSUE TITLE
Add Tags to AWS tasks

### ISSUE THREAD

**Issue by ascheman** [jenkinsci/amazon-ecs-plugin#234]
### Feature Request

I would like to see Tags on the created AWS tasks to enable CloudWatch monitoring.

**Comment by ascheman** [comment]
Hmm, it looks like AWS CloudWatch currently are not able to monitor single task executions but only the overall cluster state?

**Comment by lystopad** [comment]
Hi, dear developers!

+1 for tags

We are using your plugins and it works fine.
But our internal policy requires to tag all AWS resources, even temporary (like ecs tasks).

Could you, please, add support for tags?

**Comment by ksnehi** [comment]
+1 
We are also using the same plugin and facing this problem, it will be great if we can have the tags support for AWS ECS slave tasks.

**Comment by ascheman** [comment]
I have already implemented a solution and raised PR #235 for it. Unfortunately it does not solve my monitoring problem. But I am happy if you make use of it. 

@lystopad and @ksnehi feel free to download my change to build and run it locally on your Jenkins. Probably you find even more improvements?

**Comment by lystopad** [comment]
@ascheman , hi
Thank you for idea and for your work.
I build plugin using pr235, I did upload it and restarted jenkins service.

No luck: new ECS task, started by Jenkins has no tags, no new options was found in the Jenkins Cloud configuration.

I tried to add new cloud ECS agent, but it also has no option to define tags.

What can you advise to solve it?

Thanks.

**Comment by ascheman** [comment]
Hi @lystopad, that was our problem as well: The task definitions in ECS are tagged then, but not the task executions. As far as I can see this is not covered by my patch. Don't know if this is possible at all? Do you have an AWS support contract? You probably could clarify the opportunities with the support, before we discuss more options.

**Comment by AndyNelsenTR** [comment]
@ascheman -- I was wondering if you added similar tagging logic to ECSService.java // lines 440-449 and tag the running task request would that fix the issue?

**Comment by ascheman** [comment]
Thanks @AndyNelsenTR, this helped, I can see the tags on the task definitions now. Will extend my branch by that patch.
