### ISSUE TITLE
Allow EFS to be configured in the Jenkins plugin

### ISSUE THREAD

**Issue by keefbaker** [jenkinsci/amazon-ecs-plugin#238]
### Dependencies

None known.

### Feature Request

Please allow for configuration of EFS mounts within the Jenkins plugin. I have not found a way to do this in the plugin without configuring a task definition override, which is fine, but then I can't override ram/cpu on stages.

Or alternatively if there is a way to mount EFS in the jenkins plugin without a task definition override, can this be added to the documentation?

**Comment by Stericson** [comment]
@keefbaker See PR #237 (Merged)
