### ISSUE TITLE
Allow KernelCapabilities to be configured in plugin

### ISSUE THREAD

**Issue by vladaurosh** [jenkinsci/amazon-ecs-plugin#241]
### Dependencies

None known.

### Feature Request

Please add option to add (or drop) Linux capabilities with plugin. It is possible to create task definition and then override in plugin, but that's not most convenient way of using plugin.
This shouldn't be too difficult to add.

Described here:
https://docs.aws.amazon.com/AmazonECS/latest/userguide/task_definition_parameters.html#container_definition_linuxparameters

Java class com.amazonaws.services.ecs.model.KernelCapabilities :
https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/ecs/model/KernelCapabilities.html

Tasks launched on Fargate only support adding the SYS_PTRACE kernel capability.

Valid values: "ALL" | "AUDIT_CONTROL" | "AUDIT_WRITE" | "BLOCK_SUSPEND" | "CHOWN" | "DAC_OVERRIDE" | "DAC_READ_SEARCH" | "FOWNER" | "FSETID" | "IPC_LOCK" | "IPC_OWNER" | "KILL" | "LEASE" | "LINUX_IMMUTABLE" | "MAC_ADMIN" | "MAC_OVERRIDE" | "MKNOD" | "NET_ADMIN" | "NET_BIND_SERVICE" | "NET_BROADCAST" | "NET_RAW" | "SETFCAP" | "SETGID" | "SETPCAP" | "SETUID" | "SYS_ADMIN" | "SYS_BOOT" | "SYS_CHROOT" | "SYS_MODULE" | "SYS_NICE" | "SYS_PACCT" | "SYS_PTRACE" | "SYS_RAWIO" | "SYS_RESOURCE" | "SYS_TIME" | "SYS_TTY_CONFIG" | "SYSLOG" | "WAKE_ALARM"

**Comment by Stericson** [comment]
@vladaurosh Merged. Will deploy in the next release.
