### ISSUE TITLE
Agent label conditional expressions included in node name

### ISSUE THREAD

**Issue by berthamilton** [jenkinsci/amazon-ecs-plugin#242]
The issuse reported in https://github.com/jenkinsci/amazon-ecs-plugin/issues/228 is present in the latest versions of Jenkins and the ECS-plugin. This is caused by the fix for the following security CVE

https://www.jenkins.io/security/advisory/2021-01-13/#SECURITY-2021

The work around is currently to disable this by setting jenkins.model.Nodes.enforceNameRestrictions to false.

I did some digging and the issue relates to sanitation of the templateName. This sanitation happens only at the UI to ensure that a supplied template name conforms to a regex.
https://github.com/jenkinsci/amazon-ecs-plugin/blob/master/src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate.java#L1076

Unfortunately no such checks are present when when the ECS plugin executes a step. It simply concatenates whatever is in the step name with some random characters. 

https://github.com/jenkinsci/amazon-ecs-plugin/blob/master/src/main/java/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSTaskTemplateStepExecution.java#L48

This makes it possible to set a label expression of "linux && small" and whereupon jenkins will attempt to name the node ecs-cluster-linux&&small-wbrgg which is invalid according to the CVE, causing the exception "hudson.model.Failure: ‘&’ is an unsafe character".

Please could you take a look at this section of code and see if there's a simple/sensible fix - maybe just replace chars that fail the TEMPLATE_NAME_FORMAT with hyphens?

### Version report

Jenkins and plugins versions report:
```
Jenkins: 2.313
OS: Linux - 4.14.243-185.433.amzn2.x86_64
---
JDK_Parameter_Plugin:1.0
Office-365-Connector:4.13.2
Parameterized-Remote-Trigger:3.1.5.1
ace-editor:1.1
amazon-ecs:1.37
ansicolor:0.7.3
ant:1.11
antisamy-markup-formatter:2.1
apache-httpcomponents-client-4-api:4.5.13-1.0
authentication-tokens:1.4
aws-credentials:1.28
aws-java-sdk:1.11.854
aws-parameter-store:1.2.2
aws-secrets-manager-credentials-provider:0.5.1
bitbucket:1.1.27
blueocean:1.24.3
blueocean-autofavorite:1.2.4
blueocean-bitbucket-pipeline:1.24.3
blueocean-commons:1.24.6
blueocean-config:1.24.3
blueocean-core-js:1.24.6
blueocean-dashboard:1.24.3
blueocean-display-url:2.4.0
blueocean-events:1.24.3
blueocean-git-pipeline:1.24.3
blueocean-github-pipeline:1.24.3
blueocean-i18n:1.24.3
blueocean-jira:1.24.3
blueocean-jwt:1.24.6
blueocean-personalization:1.24.3
blueocean-pipeline-api-impl:1.24.6
blueocean-pipeline-editor:1.24.3
blueocean-pipeline-scm-api:1.24.6
blueocean-rest:1.24.6
blueocean-rest-impl:1.24.6
blueocean-web:1.24.6
bootstrap4-api:4.6.0-3
bouncycastle-api:2.20
branch-api:2.6.3
build-monitor-plugin:1.12+build.201809061734
build-name-setter:2.1.0
build-timeout:1.20
build-user-vars-plugin:1.6
checkmarx:2020.4.8
checks-api:1.7.0
cloudbees-bitbucket-branch-source:2.9.5
cloudbees-folder:6.15
command-launcher:1.5
conditional-buildstep:1.4.0
config-file-provider:3.7.0
copyartifact:1.45.3
credentials:2.3.18
credentials-binding:1.24
delivery-pipeline-plugin:1.4.2
display-url-api:2.3.4
docker-commons:1.17
docker-workflow:1.25
durable-task:1.35
ec2:1.55
echarts-api:5.0.2-1
email-ext:2.80
embeddable-build-status:2.0.3
envinject:2.3.0
envinject-api:1.7
extended-choice-parameter:0.82
extended-read-permission:3.2
extensible-choice-parameter:1.8.0
external-monitor-job:1.7
favorite:2.3.2
flexible-publish:0.15.2
font-awesome-api:5.15.2-2
generic-webhook-trigger:1.72
git:4.7.1
git-client:3.7.1
git-server:1.9
git-userContent:1.4
github:1.32.0
github-api:1.117
github-branch-source:2.9.2
github-issues:1.2.4
github-oauth:0.33
github-organization-folder:1.6
github-pullrequest:0.2.8
gradle:1.36
groovy:2.3
handlebars:1.1.1
handy-uri-templates-2-api:2.1.8-1.0
htmlpublisher:1.25
icon-shim:2.0.3
jackson2-api:2.12.3
javadoc:1.6
jaxb:2.3.0.1
jdk-tool:1.4
jenkins-design-language:1.24.6
jira:3.1.3
job-dsl:1.77
jquery:1.12.4-1
jquery-detached:1.2.1
jquery3-api:3.6.0-1
jsch:0.1.55.2
junit:1.49
label-linked-jobs:5.1.2
ldap:2.3
lockable-resources:2.10
m2release:0.16.2
mailer:1.32.1
mapdb-api:1.0.9.0
mask-passwords:2.13
matrix-auth:2.6.6
matrix-project:1.18
maven-plugin:3.8
mercurial:2.12
metrics:4.0.2.6
momentjs:1.1.1
nested-view:1.17
node-iterator-api:1.5.0
nodelabelparameter:1.7.2
okhttp-api:3.14.9
openJDK-native-plugin:1.4
pam-auth:1.6
parameterized-trigger:2.39
pipeline-build-step:2.13
pipeline-github-lib:1.0
pipeline-graph-analysis:1.10
pipeline-input-step:2.12
pipeline-milestone-step:1.3.2
pipeline-model-api:1.8.4
pipeline-model-declarative-agent:1.1.1
pipeline-model-definition:1.8.4
pipeline-model-extensions:1.8.4
pipeline-rest-api:2.19
pipeline-stage-step:2.5
pipeline-stage-tags-metadata:1.8.4
pipeline-stage-view:2.19
plain-credentials:1.7
plugin-util-api:2.1.0
popper-api:1.16.1-2
postbuild-task:1.9
postbuildscript:2.11.0
pubsub-light:1.13
rebuild:1.31
resource-disposer:0.14
rhnpush-plugin:0.5.1
run-condition:1.3
s3:0.11.5
scm-api:2.6.4
script-security:1.76
sidebar-link:1.11.0
simple-theme-plugin:0.6
snakeyaml-api:1.27.0
sonar:2.13
sse-gateway:1.24
ssh:2.6.1
ssh-agent:1.20
ssh-credentials:1.18.1
ssh-slaves:1.31.2
sshd:3.0.3
structs:1.22
templating-engine:2.1
thinBackup:1.10
throttle-concurrents:2.0.3
timestamper:1.11.8
token-macro:266.v44a80cf277fd
trilead-api:1.0.13
urltrigger:0.48
variant:1.3
windows-slaves:1.7
workflow-aggregator:2.6
workflow-api:2.42
workflow-basic-steps:2.23
workflow-cps:2.90
workflow-cps-global-lib:2.18
workflow-durable-task-step:2.38
workflow-job:2.40
workflow-multibranch:2.23
workflow-scm-step:2.12
workflow-step-api:2.23
workflow-support:3.8
ws-cleanup:0.38
xml-job-to-job-dsl:0.1.13
xray-connector:2.4.0
```

- What Operating System are you using (both controller, and any agents involved in the problem)?

```
amazon linux
```

### Reproduction steps

- Setup Jenkins with the ECS Plugin with jenkins.model.Nodes.enforceNameRestrictions not set
- Create a job with label expression that includes valid special characters (e.g. linux && small)
- Run the job and note that node will not start and the logs will fill up with  "hudson.model.Failure: ‘&’ is an unsafe character"

### Results

Expected result:

A node would start in ECS and start the job

Actual result:

Jenkins keep retrying to start the node, which fails due to the node name containing invalid characters

**Comment by MeghaPrasad** [comment]
@berthamilton Could you please let me know if this issue got resolved for you ? If yes, how did you resolve it? I am also facing same issue in Jenkins version 2.319 with ECS/Fargate plugin version 1.39.
Thanks in advance.

**Comment by carpnick** [comment]
+1

**Comment by Stericson** [comment]
@berthamilton I'm not inclined to make a change here. Your suggestion of replacing the invalid characters with valid ones won't necessarily fix this issue. Firstly, it's liable to fail anyways because there likely won't be a label that exists with the new, valid, characters. Secondly, I think it's potentially confusing for a system to change the input of a user without warning or transparency.  

I think the right course of action is what's already being done. Alerting the user that the name is unsafe and they should change it to exclude the unsafe characters. We've already done this within the GUI but there's less opportunity to do so within a declarative pipeline up until runtime. 

I'm open to additional thoughts and discussion if you have them.
