### ISSUE TITLE
enable execute command for EC2 / Fargate tasks

### ISSUE THREAD

**Issue by ascheman** [jenkinsci/amazon-ecs-plugin#245]
### Dependencies

* Switch to current [aws-java-sdk-plugin](https://github.com/jenkinsci/aws-java-sdk-plugin).

### Feature Request

As a user running ECS Fargate or EC2 tasks from Jenkins, I would like to execute commands on the running container (similar to `docker exec`) using a [new feature of AWS ECS](https://aws.amazon.com/blogs/containers/new-using-amazon-ecs-exec-access-your-containers-fargate-ec2/).

**Comment by ascheman** [comment]
Thanks for merging, @Stericson - when do you plan to release a new version of the plugin?

**Comment by Stericson** [comment]
@ascheman some time this week. The changes all look good but I want to test the final resulting version before deploying.
