### ISSUE TITLE
Allow custom tags for the ECS agent templates and created ECS tasks

### ISSUE THREAD

**Issue by ethemcemozkan** [jenkinsci/amazon-ecs-plugin#256]
### What feature do you want to see added?

The plugin creates agent templates and ECS tasks with a default set of tags. It would be really nice to define custom tags for the templates. I think custom tag support is a good idea, especially when AWS customers already utilize tags in the Cost Explorer. Using default tags in the Cost Explorer may not be good for everybody because every AWS customer can have its own spend categories.

With this feature, when an agent(the ECS task) is created, it would also have custom tags. This would allow created tasks to be visible in existing AWS Cost Reports.

**Comment by ugurkany** [comment]
I am working on this feature right now. I will create a PR at the end of this week.

**Comment by ugurkany** [comment]
PR merged. The feature will be available on the next release!
