### ISSUE TITLE
fargate fails to launch docker instance (exec: "-url": executable file not found)

### ISSUE THREAD

**Issue by lapayne** [jenkinsci/amazon-ecs-plugin#258]
when we try to launch the docker instance using the plugin we get the following error, this is on multiple docker containers including just a base centos8 image.

Stopped \| CannotStartContainerError: ResourceInitializationError: failed to create new container runtime task: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "-url": executable file not found in

I've removed the URL's for the jenkins instance and the tunnel but the error still occurs, this is running v1.41

**Comment by Stericson** [comment]
It seems you have a problem with your inbound agent container. You'll need to look into addressing that. This is an issue that's not related to this plugin.
