### ISSUE TITLE
Tag Task

### ISSUE THREAD

**Issue by charbl** [jenkinsci/amazon-ecs-plugin#261]
### What feature do you want to see added?

Is there any way we can add tag to the TASK? So that when the task is run, it will contain tags that represent the project that the job was run under?

**Comment by Stericson** [comment]
PR merged. Thanks!

**Comment by charbl** [comment]
So, I see now that you can add tags to the ECS agent templates.  Can this reference an environment variable for the value?  I am looking to "Tag" the job running in the ECS agent .... Jenkins job targets ECS on-demand worker (ECS spins up instance from plugin and template), but I want the Job to mark the task with a tag.   We have several diff orgs that use a single instance of Jenkins which offers On-Demand agents.  As org one runs a job (on-demand ECS), I would like to mark (tag) that task with org one.  I want to break down usage across the orgs when it comes to usage and cost.  Can we do this now?  If not, can we add?

**Comment by charbl** [comment]
Would like to declare the Env Variable value as the job kicks off and when the task definition is created for the ECS job, it pulls the value of the Env Var into the tag, and then the task is run on ECS using the tagged def.  So, we have 3 orgs that use a shared Jenkins.  This Jenkins runs On-Demand agents (with plugin) and when Org1 starts a job that runs on the On-demand workers, I want Org1 to set the Env Var to "Org1-PrjA". Job/Task run and are marked with a tag that has name = "Project" with value "Org1-PrjA".  So, I would guess the Env Var is on the worker node?  Just need to be able to set it to a value before the task is defined and run.
