### ISSUE TITLE
Amazon Elastic Container Service - AbstractDiskSpaceMonitor#markNodeOfflineIfDiskspaceIsTooLow

### ISSUE THREAD

**Issue by egoncearuc** [jenkinsci/amazon-ecs-plugin#262]
### Jenkins and plugins versions report

![Uploading Screenshot 2022-05-02 at 21.51.57.png…]()

### What Operating System are you using (both controller, and any agents involved in the problem)?

I'm using ECS Jenkins Slaves on Linux

### Reproduction steps

I'm invoking Jenkins Slave agent on ECS and it's failing at the end due to space issue.

`2022-05-02 18:30:31.217+0000 [id=62411] WARNING h.n.AbstractDiskSpaceMonitor#markNodeOfflineIfDiskspaceIsTooLow: Making fargate-test-114-4k591r-v7200 offline temporarily due to the lack of disk space`
 

### Expected Results

It should run as expected without space issue on ECS.
How can I increase space on ECS slave with plugin?

### Actual Results

I found an tutorial on AWS, but I can't use same in Jenkins Slave on ECS:
https://aws.amazon.com/premiumsupport/knowledge-center/ecs-fargate-increase-disk-space/

### Anything else?

Could you please help on fixing the issue with space on Jenkins Slaves on ECS with Plugin:
https://plugins.jenkins.io/amazon-ecs/

**Comment by Stericson** [comment]
You need to increase the ephemeral storage for you fargate task. You can specify this in the plugin under `ECS agent templates`

![image](https://user-images.githubusercontent.com/121938/208524266-b3a1a52c-1726-4144-9a58-854882fa685b.png)
