### ISSUE TITLE
Add ability to configure number of executors on agents

### ISSUE THREAD

**Issue by plumbuma** [jenkinsci/amazon-ecs-plugin#265]
### What feature do you want to see added?

Currently there is no mechanism to configure the number of executors on a new agent as the value has been hard coded to 1 per new agent:

[https://github.com/jenkinsci/amazon-ecs-plugin/blob/cd21b4143ac1a0d4ab41b467745161b0fa5ecaab/src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSCloud.java#L280-L286](https://github.com/jenkinsci/amazon-ecs-plugin/blob/cd21b4143ac1a0d4ab41b467745161b0fa5ecaab/src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSCloud.java#L280-L286)

There are cases in which it would be ideal to forgo the agent creation time and instead utilise an existing agent. For example, with orchestration based pipelines. 
Jenkins already enables the ability to extract the current randomly generated node name created by the amazon-ecs-plugin via `${env.NODE_NAME}`.  Subsequent/child jobs can parameterise the label/node name accordingly (e.g. `label "${NODE}"`)

**Comment by Stericson** [comment]
Merged, thanks!
