### ISSUE TITLE
Allow setting worker agent container name in multi-container task definition

### ISSUE THREAD

**Issue by nlucero** [jenkinsci/amazon-ecs-plugin#266]
### What feature do you want to see added?

I'm currently using this plugin with a custom task definition for the worker agents and facing some difficulties around the order of the containers definitions. This plugin assumes the first container is the one running the `Jenkins` worker agent (see [here](https://github.com/jenkinsci/amazon-ecs-plugin/blob/a3cffcb9d7f8b2aa79e758a0422e6535311e3ad0/src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSService.java#L418-L421)) but for some reason, my task definition (which gets generated form a `CloudFormation` template) doesn't honor the order of containers I'm setting there, which is making the plugin running an unrelated container as the agent one and causing issues.

It would be great if instead of relying on the order of the containers in the task definition, we could set the name of the container running the `Jenkins` worker agent in the plugin configuration.

**Comment by Stericson** [comment]
This will be in the next release. Thanks for the PR!
