### ISSUE TITLE
Expand/Collapse ECS agent templates

### ISSUE THREAD

**Issue by LeoDOD** [jenkinsci/amazon-ecs-plugin#283]
### What feature do you want to see added?

Currently, the Configure Cloud page just grows in size as you create new Agent Templates. It would be useful to have the templates collapsed, and just display the label name, and if you need to make changes you can expand them.

**Comment by facuparedes-litebox** [comment]
👍 We also need this, is there any workaround ?

**Comment by LeoDOD** [comment]
I am using the CaC plugin to udpate the templates, but I don't like having to reload the entire config to add a new agent.

**Comment by Stericson** [comment]
Will be in next release
