### ISSUE TITLE
What does "Maximum Agents" actually do?

### ISSUE THREAD

**Issue by jonbrohauge** [jenkinsci/amazon-ecs-plugin#293]
### Describe your use-case which is not covered by existing documentation.

I have a hard time trying to figure out what exactly the value for "Maximum Agents" does. I do not find the "one liner comment" currently associated with the property informational enough. I'd love to contribute to write some documentation on the different properties, if I knew what each property did.

For an example, using release 1.46, I have set the property to 10, and Jenkins still created more than 10 agents. So my guess is that I misunderstand what the explainer says.

**Comment by grahamrhay** [comment]
see: https://github.com/jenkinsci/amazon-ecs-plugin/issues/269
