### ISSUE TITLE
Which "tags" can be used?

### ISSUE THREAD

**Issue by jonbrohauge** [jenkinsci/amazon-ecs-plugin#294]
### Describe your use-case which is not covered by existing documentation.

Besides the point that it is not currently possible to add tags via the UI, and I get a NPE when not defining any tags (probably related issue: #290), how do you write a tag? Which tags are viable? Is there a list of viable tags? How do I define my own tags?

Basically any information on tags is appreciated.

**Comment by Stericson** [comment]
Tags for be any key:value pair. You define these as needed.
