### ISSUE TITLE
Fargate workers cant access Nexus repository and Soanrqube

### ISSUE THREAD

**Issue by LeBakii** [jenkinsci/amazon-ecs-plugin#296]
I have an EC2 machine and in this machine I have Jenkins master, nexus repository and sonarqube. And with this jenkins fargate plugin I create fargate containers for jenkins workers. And this workers in same subnet in EC2 machine and same vpc. But when I use whistlist on 443 port for nexus and sonarqube, created fargate container cant access to nexus and sonarqube but they are on same public subnet. What should I do for the connection. I use different security groups for EC2 machine and fargate conrtainers but subnets and vpc is same.

I need to close jenkins master nexus and sonarqube login pages so I need to use whistlist right other way can't close? what should I do for comminication fargate container and EC2 machine for nexus and sonarqube?

Update: 
Subnet is public subnet. 
Security group for fargate outbound rules is all open. 
The error is "Connection time out".

**Comment by Stericson** [comment]
This is not an issue with the plugin. It sounds like you might have some networking/routing issues that might be preventing communication.
