### ISSUE TITLE
Windows Container never start running

### ISSUE THREAD

**Issue by willerpp** [jenkinsci/amazon-ecs-plugin#297]
### Jenkins and plugins versions report

<details>
I have been trying to create dynamic agents with the plug in for a fargate cluster, with the windows image for the agent : jenkins/inbound-agent:windowsservercore-ltsc2019  and Windows Server Core 2019 for the SO image base for the host.

I setup everything in the plugin and all works fine until the time that the container show up and start the creation of it.
The task is created successful, the container is being created but it never moves to the running state, it never go out of the pending state.

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Windows Server Core 2019,  Host and agent

### Reproduction steps

Setup inside the plugin a windows cluster with fargate, 
the image: jenkins/inbound-agent:windowsservercore-ltsc2019, 
Operating System Family:  Windows CORE 2019, 
architecture: X86_64
networkmode: awsvpc
filesystem root: C:\Users\jenkins\
Platform version : latest
soft memory: 2048
cpu: 1024

### Expected Results

Creation of an agent dynamic for windows containers

### Actual Results

The task definition is created, the task is created, the container is being created but never enter in the running stste, its always in pending state.
I have setup the same plugin but with a fargate task in linux with all the parameters for linux including the linux image and it works perfectly but for windows it didn't work.
any advice????

**Comment by bradq** [comment]
@willerpp This is very unlikely a bug with the plugin itself. More likely, your agent isn't properly phoning home. Ensure you can telnet to port 50000 from the launched container, and check agent logs on the container itself (which, depending on your image, certainly *should* be in the stdout as well). The ECS plugin logs on Jenkins itself may have something as a last resort. 

Pending state is nearly always the result of the task having been launched, but never successfully communicating with the plugin.
