### ISSUE TITLE
Could not find matching constructor for: com.cloudbees.jenkins.plugins.amazonecs.ECSTaskTemplate

### ISSUE THREAD

**Issue by mahernoz-d** [jenkinsci/amazon-ecs-plugin#302]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.303.2
OS: Linux - 4.14.248-189.473.amzn2.x86_64
---
Office-365-Connector:4.17.0
ace-editor:1.1
amazon-ecr:1.73.v741d474abe74
amazon-ecs:1.41
ant:475.vf34069fef73c
antisamy-markup-formatter:2.7
apache-httpcomponents-client-4-api:4.5.13-1.0
artifactory:3.17.0
authentication-tokens:1.4
authorize-project:1.4.0
aws-credentials:191.vcb_f183ce58b_9
aws-java-sdk:1.12.287-357.vf82d85a_6eefd
aws-java-sdk-cloudformation:1.12.287-357.vf82d85a_6eefd
aws-java-sdk-codebuild:1.12.287-357.vf82d85a_6eefd
aws-java-sdk-ec2:1.12.287-357.vf82d85a_6eefd
aws-java-sdk-ecr:1.12.287-357.vf82d85a_6eefd
aws-java-sdk-ecs:1.12.287-357.vf82d85a_6eefd
aws-java-sdk-efs:1.12.287-357.vf82d85a_6eefd
aws-java-sdk-elasticbeanstalk:1.12.287-357.vf82d85a_6eefd
aws-java-sdk-iam:1.12.287-357.vf82d85a_6eefd
aws-java-sdk-logs:1.12.287-357.vf82d85a_6eefd
aws-java-sdk-minimal:1.12.287-357.vf82d85a_6eefd
aws-java-sdk-sns:1.12.287-357.vf82d85a_6eefd
aws-java-sdk-sqs:1.12.287-357.vf82d85a_6eefd
aws-java-sdk-ssm:1.12.287-357.vf82d85a_6eefd
aws-lambda:0.5.10
aws-secrets-manager-credentials-provider:1.2.0
aws-secrets-manager-secret-source:0.0.2
aws-sqs:2.0.1
blueocean:1.25.5
blueocean-autofavorite:1.2.5
blueocean-bitbucket-pipeline:1.25.5
blueocean-commons:1.25.5
blueocean-config:1.25.5
blueocean-core-js:1.25.5
blueocean-dashboard:1.25.5
blueocean-display-url:2.4.1
blueocean-events:1.25.5
blueocean-executor-info:1.25.5
blueocean-git-pipeline:1.25.5
blueocean-github-pipeline:1.25.5
blueocean-i18n:1.25.5
blueocean-jira:1.25.5
blueocean-jwt:1.25.5
blueocean-personalization:1.25.5
blueocean-pipeline-api-impl:1.25.5
blueocean-pipeline-editor:1.25.5
blueocean-pipeline-scm-api:1.25.5
blueocean-rest:1.25.5
blueocean-rest-impl:1.25.5
blueocean-web:1.25.5
bootstrap4-api:4.6.0-5
bootstrap5-api:5.1.3-6
bouncycastle-api:2.25
branch-api:2.1046.v0ca_37783ecc5
build-monitor-plugin:1.13+build.202202112334
caffeine-api:2.9.3-65.v6a_47d0f4d1fe
checks-api:1.7.4
cloudbees-bitbucket-branch-source:762.v969cfe087fc0
cloudbees-folder:6.722.v8165b_a_cf25e9
codecommit-url-helper:0.0.3
codedeploy:1.23
command-launcher:81.v9c2cb_cb_db_392
config-file-provider:3.8.2
configuration-as-code:1512.vb_79d418d5fc8
credentials:2.6.1.1
credentials-binding:1.27.1
display-url-api:2.3.5
docker-commons:1.19
docker-workflow:1.28
durable-task:501.ve5d4fc08b0be
ec2:1.68
echarts-api:5.3.2-1
email-ext:2.87
extended-read-permission:3.2
external-monitor-job:191.v363d0d1efdf8
favorite:2.3.3.1
font-awesome-api:6.0.0-1
git:4.11.3
git-client:3.11.0
git-parameter:0.9.14
git-server:1.11
github:1.34.3
github-api:1.303-400.v35c2d8258028
github-branch-source:2.11.4
github-scm-trait-commit-skip:0.4.0
gradle:1.39.4
groovy:2.4
h2-api:1.4.199
handlebars:3.0.8
handy-uri-templates-2-api:2.1.8-22.v77d5b_75e6953
htmlpublisher:1.30
ignore-committer-strategy:1.0.4
ivy:2.2
jackson2-api:2.13.3-285.vc03c0256d517
javadoc:217.v905b_86277a_2a_
javax-activation-api:1.2.0-3
javax-mail-api:1.6.2-6
jaxb:2.3.6-1
jdk-tool:1.5
jenkins-design-language:1.25.5
jira:3.7.1
jjwt-api:0.11.5-77.v646c772fddb_0
job-dsl:1.81
jquery:1.12.4-1
jquery-detached:1.2.1
jquery-ui:1.0.2
jquery3-api:3.6.0-3
jsch:0.1.55.2
junit:1.53.0.1
keycloak:2.3.0
ldap:2.9
lockable-resources:2.16
mailer:414.vcc4c33714601
matrix-auth:3.1.5
matrix-project:772.v494f19991984
maven-plugin:3.16
mercurial:2.16.2
metrics:4.0.2.8.1
mina-sshd-api-common:2.8.0-21.v493b_6b_db_22c6
mina-sshd-api-core:2.8.0-21.v493b_6b_db_22c6
modernstatus:1.3
momentjs:1.1.1
msbuild:1.30
node-iterator-api:1.5.1
okhttp-api:4.9.3-105.vb96869f8ac3a
ownership:0.13.0
pam-auth:1.6.1
parameterized-scheduler:1.0
pipeline-aws:1.43
pipeline-build-step:2.18
pipeline-graph-analysis:1.11
pipeline-groovy-lib:598.vcd66b_a_336510
pipeline-input-step:449.v77f0e8b_845c4
pipeline-maven:3.10.0
pipeline-milestone-step:101.vd572fef9d926
pipeline-model-api:1.9.3
pipeline-model-declarative-agent:1.1.1
pipeline-model-definition:1.9.3
pipeline-model-extensions:1.9.3
pipeline-rest-api:2.24
pipeline-stage-step:293.v200037eefcd5
pipeline-stage-tags-metadata:1.9.3
pipeline-stage-view:2.24
pipeline-utility-steps:2.13.0
plain-credentials:1.8
plugin-util-api:2.16.0
popper-api:1.16.1-3
popper2-api:2.11.5-1
postbuildscript:3.1.0-375.v3db_cd92485e1
pubsub-light:1.16
role-strategy:484.v8a_a_e4b_d785fd
run-condition:1.5
scalable-amazon-ecs:1.0
scm-api:608.vfa_f971c5a_a_e9
scmskip:1.0.3
script-security:1138.v8e727069a_025
seleniumhtmlreport:1.1
snakeyaml-api:1.30.2-76.vc104f7ce9870
sonar:2.14
sse-gateway:1.25
ssh-credentials:277.v95c2fec1c047
ssh-slaves:1.806.v2253cedd3295
sshd:3.242.va_db_9da_b_26a_c3
statistics-gatherer:2.0.3
structs:324.va_f5d6774f3a_d
testng-plugin:555.va0d5f66521e3
timestamper:1.18
token-macro:308.v4f2b_ed62b_b_16
trilead-api:1.0.13
variant:1.4
windows-slaves:1.8.1
workflow-aggregator:578.vf9a_f99755f4a_
workflow-api:1153.vb_912c0e47fb_a_
workflow-basic-steps:2.24
workflow-cps:2660.vb_c0412dc4e6d
workflow-cps-global-lib:588.v576c103a_ff86
workflow-durable-task-step:2.40
workflow-job:1145.v7f2433caa07f
workflow-multibranch:716.vc692a_e52371b_
workflow-scm-step:400.v6b_89a_1317c9a_
workflow-step-api:639.v6eca_cd8c04a_a_
workflow-support:813.vb_d7c3d2984a_0
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Amazon Linux 2

### Reproduction steps

1. Go to Manage Jenkins, Script Console. 
2. Ensure plugin version 1.41 of Amazon Elastic Container Service (ECS) / Fargate
3. Run the script taken from test code of ecs fargate plugin (our script is derived from the same)

package com.cloudbees.jenkins.plugins.amazonecs.pipeline;

import com.cloudbees.jenkins.plugins.amazonecs.ECSCloud;
import com.cloudbees.jenkins.plugins.amazonecs.ECSTaskTemplate;
import com.cloudbees.jenkins.plugins.amazonecs.SerializableSupplier;
import jenkins.model.Jenkins;
import org.jenkinsci.plugins.workflow.steps.BodyExecutionCallback;
import org.jenkinsci.plugins.workflow.steps.BodyInvoker;

import java.util.Arrays;
import java.util.Random;
import java.util.UUID;

    Random r = new Random();
         ECSTaskTemplate expected = new ECSTaskTemplate(
                "template-name",
                "child-label",
                UUID.randomUUID().toString(),
                null,
                "image-override",
                UUID.randomUUID().toString(),
                UUID.randomUUID().toString(),
                "LINUX",
                "X86_64",
                false,
                null,
                UUID.randomUUID().toString(),
                UUID.randomUUID().toString(),
                false,
                null,
                r.nextInt(123),
                r.nextInt(456),
                r.nextInt(1024),
                r.nextInt(200),
                UUID.randomUUID().toString(),
                UUID.randomUUID().toString(),
                r.nextBoolean(),
                r.nextBoolean(),
                UUID.randomUUID().toString(),
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                UUID.randomUUID().toString(),
                null,
                "override-task-role",
                null,
                r.nextInt(123),
                false);

### Expected Results

Result: templateName: 
label: child-label
taskDefinitionOverride: e0b047e2-057c-4c9b-ae41-df7b471f5db0
dynamicTaskDefinitionOverride: null
image: image-override
remoteFSRoot: 8e5447e4-b517-4b0d-995b-acd86a651806
memory: 43
memoryReservation: 404
cpu: 588
ephemeralStorageSizeInGiB: 193
sharedMemorySize: 59
subnets: 702e533e-3d35-4f1c-a5d9-0087c847f5e4
securityGroups: ce3f9ec0-c724-415d-b497-2f99e842c860
assignPublicIp: true
dnsSearchDomains: null
entrypoint: null
taskrole: override-task-role
executionRole: d957e431-247d-4894-bcd0-f9d8aaa232e6
repositoryCredentials: 9a91ee80-a989-4b10-9986-230977a3bf3f
jvmArgs: null
mountPoints: null
efsMountPoints: null
launchType: a96028eb-a290-46db-87c3-76151e309e31
operatingSystemFamily: LINUX
cpuArchitecture: X86_64
defaultCapacityProvider: false
networkMode: aa422108-c5a8-4f6d-8d7e-12e79fdbe3d2
privileged: false
uniqueRemoteFSRoot: false
platformVersion: null
containerUser: 532b30d1-77d8-424a-836e-de8fc0d8db8f
kernelCapabilities: null
environments: null
extraHosts: null
portMappings: null
placementStrategies: null
capacityProviderStrategies: null
logDriver: null
logDriverOptions: null
inheritFrom: null
enableExecuteCommand: false

### Actual Results

groovy.lang.GroovyRuntimeException: Could not find matching constructor for: com.cloudbees.jenkins.plugins.amazonecs.ECSTaskTemplate(java.lang.String, java.lang.String, null, null, java.lang.String, null, java.lang.String, null, null, java.lang.Boolean, null, java.lang.String, java.lang.String, java.lang.Boolean, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.Integer, null, null, null, java.lang.Boolean, java.lang.Boolean, null, null, java.util.Arrays$ArrayList, null, null, java.util.Arrays$ArrayList, null, null, null, null, null, null, java.lang.Integer, java.lang.Boolean)

### Anything else?

There are two jenkins servers (same version number: [Jenkins 2.303.2] and Both having plugin version 1.41 of Amazon Elastic Container Service (ECS) / Fargate, one is giving the expected result, the other is giving this error. 

Checked all the parameters but cannot find the cause of the issue.

**Comment by mahernoz-d** [comment]
Is this forum active, its been 7 days, no reply.

**Comment by Stericson** [comment]
@mahernoz-d I'd check and make certain that both Jenkins are actually running the same plugin version. The latest version is 1.46.

**Comment by mahernoz-d** [comment]
They are running the same version.
