### ISSUE TITLE
Support Parallel ECS agent spawning

### ISSUE THREAD

**Issue by alexanderrtaylor** [jenkinsci/amazon-ecs-plugin#85]
When using a `parallel` within a pipeline I would like to use the ECS plugin to spawn agents. The problem is that when I make the request out to spawn multiple ECS agents they spawn one at a time. It seems the the ECS plugin can only spawn one agent until that agent comes online fully. Which means they spawn in a potentially random order even though the cloud provisioner knows that all the agents are of the ECS type.

It would be great if the ECS plugin would support the multithreaded approach to spawning agents like EC2 or docker cloud plugins.

I am not sure of the AWS APIs support such a thing but it would be a great feature to have.

**Comment by pgarbe** [comment]
Does [https://github.com/jenkinsci/amazon-ecs-plugin#my-parallel-jobs-dont-start-at-the-same-time](https://github.com/jenkinsci/amazon-ecs-plugin#my-parallel-jobs-dont-start-at-the-same-time) answer your question?

**Comment by alexanderrtaylor** [comment]
>Jenkins calls the ECS plugin multiple times to get the total number of agents running.

This is what appears to not be happening. You are getting the "I need x instances from ec2 cloud" messages in the logs but it does not call the ECS plugin multiple times instantly(like it does with any other cloud-type agent) in order to spin up an ECS plugin. Each time it has to wait for the EC2 instance to come up and connect to Jenkins before spinning up the next one which leads to about a 15-20 second lag time for each subsequent parallel thread.

Does that answer your question @pgarbe

**Comment by pgarbe** [comment]
Can you point me to the code how other plugins handle it parallel? From my understanding the plugin itself does not know about the pipeline and if something is parallel or not. It just gets a call to the `provision()` [method](https://github.com/jenkinsci/amazon-ecs-plugin/blob/master/src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSCloud.java#L215). It's similar what the Kubernetes plugin is [doing](https://github.com/jenkinsci/kubernetes-plugin/blob/master/src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java#L448). 

You can tweak the behaviour a bit by applying [this](https://github.com/jenkinsci/kubernetes-plugin#over-provisioning-flags) settings.

**Comment by alexanderrtaylor** [comment]
@pgarbe It looks like [this code](https://github.com/jenkinsci/kubernetes-plugin/blob/master/src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesCloud.java#L457) where he is grabbing all the labels which are requested and then adds them to be provisioned may be the fix. Whereas in [the ECS plugin](https://github.com/jenkinsci/amazon-ecs-plugin/blob/master/src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSCloud.java#L226) it only grabs the next label and then creates that agent. So even if they were the same label, you would only provision one. 

This is kind of just a guess at this point but it does seem to make sense since [the docker plugin](https://github.com/jenkinsci/docker-plugin/blob/3c26f25d264f6da13a9823662f2237e25f721ba8/src/main/java/com/nirima/jenkins/plugins/docker/DockerCloud.java#L324) appears to do the same

**Comment by pgarbe** [comment]
@alexanderrtaylor I see your point. From my understanding, `Label` is not a list but a single value. The expectation of the ECS plugin is, that this value is unique enough to return only one template and not a list of templates. Actually, I don't really understand why the Docker and Kubernetes plugins expect a list of templates.

For example, when your Jenkinsfile contains two parallel stages with different labels, the `provision()` method is called twice in parallel. If both stages use the same label, `provision()` is likely to be called only once. After that Jenkins waits a bit and if there's still some demand for an agent with the matching label it calls the `provision()` method again. 

This is my understanding from the [docs](https://javadoc.jenkins-ci.org/hudson/slaves/Cloud.html#provision-hudson.model.Label-int-) and their [implementation](https://github.com/jenkinsci/jenkins/blob/399c8ba40ab9ccab8e70dcacfdd396b0c2e654d7/core/src/main/java/hudson/slaves/NodeProvisioner.java#L622)

**Comment by webratz** [comment]
overall setting the following options speeds up the launching a bit `-Dhudson.slaves.NodeProvisioner.initialDelay=0 -Dhudson.slaves.NodeProvisioner.MARGIN=50 -Dhudson.slaves.NodeProvisioner.MARGIN0=0.85`

**Comment by svaranasi-traderev** [comment]
What these ^ settings help to eliminate is:
- Prevent Jenkins from waiting for an ECS node to free-up so it can be re-used for another build.

What it doesn't eliminate is:
- Prevent Jenkins from waiting for an ECS node to start and connect to master before spinning up a new node. [This behaviour](https://github.com/jenkinsci/jenkins/blob/399c8ba40ab9ccab8e70dcacfdd396b0c2e654d7/core/src/main/java/hudson/slaves/NodeProvisioner.java#L661). 

And I believe this issue was opened to request help to eliminate the latter scenario. 

Can a Jenkins-level behaviour be tweaked or modified by a plugin?

**Comment by bradq** [comment]
@svaranasi-traderev I don't believe there's a workaround established for that behavior, but you can avoid the effects by using `inheritFrom` inside an `agent { ecs {} }` block, e.g. 

```
agent {
  ecs {
    inheritFrom 'java-build-tools-jnlp'
  }
}
```
rather than `agent { label 'java-build-tools-jnlp' }`. 

Using the `inheritFrom` templating engine effects a new, ephemeral label with a unique name. Using the NodeProvisioner tweaks with this approach, I've seen little to no delay spawning multiple parallel ECS tasks.
