### ISSUE TITLE
java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to com.cloudbees.jenkins.plugins.amazonecs.ECSTaskTemplate$LogDriverOption

### ISSUE THREAD

**Issue by atifrasheed79** [jenkinsci/amazon-ecs-plugin#87]
Hi, I am using groovy init and bootstrap scripts to configure my Jenkins. After startup, it seems Jenkins is not reading the ECSTemplate properly. However, if I go to Jenkins Configuration again (Manage Jenkins -> Configuration), and just save it again, without changing anything, it starts working, I mean it starts provisioning the Agents. 

I get below error/exception in my logs before saving the config again.

INFO: ECS Agent base-agent linux provisioning successfully completed. We have now 3 computer(s)
Mar 29, 2019 11:43:46 AM com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
WARNING: [linux-gd6pf]: Error in provisioning; agent=com.cloudbees.jenkins.plugins.amazonecs.ECSSlave[linux-gd6pf]
java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to com.cloudbees.jenkins.plugins.amazonecs.ECSTaskTemplate$LogDriverOption
at com.cloudbees.jenkins.plugins.amazonecs.ECSTaskTemplate.getLogDriverOptionsMap(ECSTaskTemplate.java:473)
at com.cloudbees.jenkins.plugins.amazonecs.ECSService.registerTemplate(ECSService.java:209)
at com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher.getTaskDefinition(ECSLauncher.java:200)
at com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher.launch(ECSLauncher.java:106)
at hudson.slaves.SlaveComputer$1.call(SlaveComputer.java:294)
at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)

**Comment by pgarbe** [comment]
Which version are you using? Can you make a diff of the config.xml after your init script and after you click on save in the ui?

**Comment by atifrasheed79** [comment]
I just did a test with 2.164. Here is config.xml.diff

`
45,56c45,74
<             <com.cloudbees.jenkins.plugins.amazonecs.ECSTaskTemplate_-LogDriverOption>
<               <name>awslogs-group</name>
<               <value>RES-Transformation-Jenkins</value>
<             </com.cloudbees.jenkins.plugins.amazonecs.ECSTaskTemplate_-LogDriverOption>
<             <com.cloudbees.jenkins.plugins.amazonecs.ECSTaskTemplate_-LogDriverOption>
<               <name>awslogs-region</name>
<               <value>ap-southeast-2</value>
<             </com.cloudbees.jenkins.plugins.amazonecs.ECSTaskTemplate_-LogDriverOption>
<             <com.cloudbees.jenkins.plugins.amazonecs.ECSTaskTemplate_-LogDriverOption>
<               <name>awslogs-stream-prefix</name>
<               <value>FARGATE</value>
<             </com.cloudbees.jenkins.plugins.amazonecs.ECSTaskTemplate_-LogDriverOption>
---
>             <linked-hash-map>
>               <entry>
>                 <string>name</string>
>                 <string>awslogs-group</string>
>               </entry>
>               <entry>
>                 <string>value</string>
>                 <string>RES-Transformation-Jenkins</string>
>               </entry>
>             </linked-hash-map>
>             <linked-hash-map>
>               <entry>
>                 <string>name</string>
>                 <string>awslogs-region</string>
>               </entry>
>               <entry>
>                 <string>value</string>
>                 <string>ap-southeast-2</string>
>               </entry>
>             </linked-hash-map>
>             <linked-hash-map>
>               <entry>
>                 <string>name</string>
>                 <string>awslogs-stream-prefix</string>
>               </entry>
>               <entry>
>                 <string>value</string>
>                 <string>FARGATE</string>
>               </entry>
>             </linked-hash-map>
77,88c95,124
<             <com.cloudbees.jenkins.plugins.amazonecs.ECSTaskTemplate_-LogDriverOption>
<               <name>awslogs-group</name>
<               <value>RES-Transformation-Jenkins</value>
<             </com.cloudbees.jenkins.plugins.amazonecs.ECSTaskTemplate_-LogDriverOption>
<             <com.cloudbees.jenkins.plugins.amazonecs.ECSTaskTemplate_-LogDriverOption>
<               <name>awslogs-region</name>
<               <value>ap-southeast-2</value>
<             </com.cloudbees.jenkins.plugins.amazonecs.ECSTaskTemplate_-LogDriverOption>
<             <com.cloudbees.jenkins.plugins.amazonecs.ECSTaskTemplate_-LogDriverOption>
<               <name>awslogs-stream-prefix</name>
<               <value>FARGATE</value>
<             </com.cloudbees.jenkins.plugins.amazonecs.ECSTaskTemplate_-LogDriverOption>
---
>             <linked-hash-map>
>               <entry>
>                 <string>name</string>
>                 <string>awslogs-group</string>
>               </entry>
>               <entry>
>                 <string>value</string>
>                 <string>RES-Transformation-Jenkins</string>
>               </entry>
>             </linked-hash-map>
>             <linked-hash-map>
>               <entry>
>                 <string>name</string>
>                 <string>awslogs-region</string>
>               </entry>
>               <entry>
>                 <string>value</string>
>                 <string>ap-southeast-2</string>
>               </entry>
>             </linked-hash-map>
>             <linked-hash-map>
>               <entry>
>                 <string>name</string>
>                 <string>awslogs-stream-prefix</string>
>               </entry>
>               <entry>
>                 <string>value</string>
>                 <string>FARGATE</string>
>               </entry>
>             </linked-hash-map>
92d127
<       <credentialsId></credentialsId>
95d129
<       <tunnel></tunnel>
98c132
<       <slaveTimeoutInSeconds>900</slaveTimeoutInSeconds>
---
>       <slaveTimeoutInSeconds>300</slaveTimeoutInSeconds>
101d134
<   <quietPeriod>5</quietPeriod>
`

**Comment by pgarbe** [comment]
Hi @atifrasheed79 , which version of the ECS plugin are you using?

**Comment by atifrasheed79** [comment]
Hi Philip, it's 1.19. Thanks.

**Comment by atifrasheed79** [comment]
@pgarbe  I thought the issue is in the backlog if no one is currently working on it but it has been closed by the bot. Could you please re-open it?

**Comment by markyjackson-taulia** [comment]
Sorry for not catching this @atifrasheed79
