### ISSUE TITLE
Jenkins is not creating task definition for Fargate

### ISSUE THREAD

**Issue by ndesai15** [jenkinsci/amazon-ecs-plugin#89]
After doing some round of testing, I realized that Jenkins is not creating Fargate task definition automatically using this plugin. If I pass already created Task definition ARN in Task Definition Override, it works fine & spins up Fargate slaves.

For managed EC2 run(old-ECS), it is successfully creating task definition & running it on cluster.

![image](https://user-images.githubusercontent.com/14083900/55803911-eaad3d80-5aa0-11e9-9df6-a965d8b9211d.png)

**Comment by pgarbe** [comment]
Can you check in your logs which exception is thrown?

**Comment by alineprattiezops** [comment]
> Can you check in your logs which exception is thrown?

the same here =/
Task apear in aws, but no generates echo in Jenkins output.
And the Command task don't has the echo.

Jenkins job output stucks in:
[Pipeline] Start of Pipeline
[Pipeline] stage
[Pipeline] { (Test)
[Pipeline] node
Still waiting to schedule task
‘default-0l859’ is offline

Jenkins log:
Apr 11, 2019 8:42:17 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSService registerTemplate
Match on task role: true
Apr 11, 2019 8:42:17 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSService registerTemplate
Match on execution role: true
Apr 11, 2019 8:42:17 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSService registerTemplate
Match on network mode: true
Apr 11, 2019 8:42:17 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher runECSTask
[default-0l859]: Starting agent with task definition arn:aws:ecs:us-east-1:xxxxxxxxxxx:task-definition/default-fargate-template:1}
Apr 11, 2019 8:42:18 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher runECSTask
[default-0l859]: Agent started with task arn : arn:aws:ecs:us-east-1:xxxxxxxxxxx:task/e81a38df-c91a-40bd-bcae-c8e45e5eef1a
Apr 11, 2019 8:42:18 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
[default-0l859]: TaskArn: arn:aws:ecs:us-east-1:xxxxxxxxxxx:task/e81a38df-c91a-40bd-bcae-c8e45e5eef1a
Apr 11, 2019 8:42:18 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
[default-0l859]: TaskDefinitionArn: arn:aws:ecs:us-east-1:xxxxxxxxxxx:task-definition/default-fargate-template:1
Apr 11, 2019 8:42:18 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
[default-0l859]: ClusterArn: arn:aws:ecs:us-east-1:xxxxxxxxxxx:cluster/default
Apr 11, 2019 8:42:18 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
[default-0l859]: ContainerInstanceArn: null
Apr 11, 2019 8:42:18 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
[default-0l859]: Waiting for agent to start
Apr 11, 2019 8:42:20 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
[default-0l859]: Waiting for agent to start
Apr 11, 2019 8:42:21 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
[default-0l859]: Waiting for agent to start
Apr 11, 2019 8:42:22 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
[default-0l859]: Waiting for agent to start
Apr 11, 2019 8:42:24 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
[default-0l859]: Waiting for agent to start
Apr 11, 2019 8:42:25 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
[default-0l859]: Waiting for agent to start
Apr 11, 2019 8:42:26 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
[default-0l859]: Waiting for agent to start
Apr 11, 2019 8:42:27 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
[default-0l859]: Waiting for agent to start
Apr 11, 2019 8:42:29 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
[default-0l859]: Waiting for agent to start
Apr 11, 2019 8:42:30 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
[default-0l859]: Waiting for agent to start
Apr 11, 2019 8:42:31 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
[default-0l859]: Waiting for agent to start
Apr 11, 2019 8:42:33 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
[default-0l859]: Waiting for agent to start
Apr 11, 2019 8:42:34 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
[default-0l859]: Waiting for agent to start
Apr 11, 2019 8:42:35 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
[default-0l859]: Waiting for agent to start
Apr 11, 2019 8:42:37 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
[default-0l859]: Waiting for agent to start
Apr 11, 2019 8:42:38 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
[default-0l859]: Waiting for agent to start
Apr 11, 2019 8:42:39 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
[default-0l859]: Waiting for agent to start
Apr 11, 2019 8:42:40 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
[default-0l859]: Waiting for agent to start
Apr 11, 2019 8:42:42 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
[default-0l859]: Waiting for agent to start
Apr 11, 2019 8:42:43 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
[default-0l859]: Waiting for agent to start
Apr 11, 2019 8:42:44 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
[default-0l859]: Waiting for agent to start
Apr 11, 2019 8:42:46 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
[default-0l859]: Waiting for agent to start
Apr 11, 2019 8:42:47 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
[default-0l859]: Waiting for agent to start
Apr 11, 2019 8:42:48 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
[default-0l859]: Waiting for agent to start
Apr 11, 2019 8:42:49 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
[default-0l859]: Waiting for agent to start
Apr 11, 2019 8:42:51 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
[default-0l859]: Waiting for agent to start
Apr 11, 2019 8:42:52 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
[default-0l859]: Waiting for agent to start
Apr 11, 2019 8:42:53 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
[default-0l859]: Waiting for agent to start
Apr 11, 2019 8:42:55 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
[default-0l859]: Waiting for agent to start
Apr 11, 2019 8:42:56 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
[default-0l859]: Waiting for agent to start
Apr 11, 2019 8:42:57 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
[default-0l859]: Waiting for agent to start
Apr 11, 2019 8:42:58 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
[default-0l859]: Waiting for agent to start
Apr 11, 2019 8:43:00 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
[default-0l859]: Waiting for agent to start
Apr 11, 2019 8:46:26 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
[default-0l859]: Waiting for agent to connect
Apr 11, 2019 8:48:30 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
[default-0l859]: Waiting for agent to connect
Apr 11, 2019 8:48:31 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSSlave _terminate
[default-0l859]: Stopping: TaskArn arn:aws:ecs:us-east-1:xxxxxxxxxxx:task/e81a38df-c91a-40bd-bcae-c8e45e5eef1a, ClusterArn arn:aws:ecs:us-east-1:xxxxxxxxxxx:cluster/default
Apr 11, 2019 8:48:31 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSService stopTask
Delete ECS agent task: arn:aws:ecs:us-east-1:xxxxxxxxxxx:task/e81a38df-c91a-40bd-bcae-c8e45e5eef1a
Apr 11, 2019 8:48:31 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
[default-0l859]: Waiting for agent to connect
Apr 11, 2019 8:48:32 PM WARNING com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
[default-0l859]: Error in provisioning; agent=com.cloudbees.jenkins.plugins.amazonecs.ECSSlave[default-0l859]
java.lang.IllegalStateException: Node was deleted, computer is null
	at com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher.launch(ECSLauncher.java:156)
	at hudson.slaves.SlaveComputer$1.call(SlaveComputer.java:294)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Apr 11, 2019 8:48:32 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSSlave _terminate
[default-0l859]: Stopping: TaskArn arn:aws:ecs:us-east-1:xxxxxxxxxxx:task/e81a38df-c91a-40bd-bcae-c8e45e5eef1a, ClusterArn arn:aws:ecs:us-east-1:xxxxxxxxxxx:cluster/default
Apr 11, 2019 8:48:32 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSService stopTask
Delete ECS agent task: arn:aws:ecs:us-east-1:xxxxxxxxxxx:task/e81a38df-c91a-40bd-bcae-c8e45e5eef1a
Apr 11, 2019 8:48:37 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSCloud provision
Asked to provision 1 agent(s) for: ecs
Apr 11, 2019 8:48:37 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSCloud provision
In provisioning : []
Apr 11, 2019 8:48:37 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSCloud provision
Excess workload after pending ECS agents: 1
Apr 11, 2019 8:48:37 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSCloud provision
Will provision ECS Agent ecs, for label: ecs
Apr 11, 2019 8:48:37 PM INFO hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
Started provisioning ECS Agent ecs from default with 1 executors. Remaining excess workload: 0
Apr 11, 2019 8:48:47 PM INFO hudson.slaves.NodeProvisioner$2 run
ECS Agent ecs provisioning successfully completed. We have now 2 computer(s)
Apr 11, 2019 8:48:47 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSService registerTemplate
Match on container definition: true
Apr 11, 2019 8:48:47 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSService registerTemplate
Match on volumes: true
Apr 11, 2019 8:48:47 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSService registerTemplate
Match on task role: true
Apr 11, 2019 8:48:47 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSService registerTemplate
Match on execution role: true
Apr 11, 2019 8:48:47 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSService registerTemplate
Match on network mode: true
Apr 11, 2019 8:48:47 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher runECSTask
[default-c5r21]: Starting agent with task definition arn:aws:ecs:us-east-1:xxxxxxxxxxx:task-definition/default-fargate-template:1}
Apr 11, 2019 8:48:48 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher runECSTask
[default-c5r21]: Agent started with task arn : arn:aws:ecs:us-east-1:xxxxxxxxxxx:task/4a5ca5a6-b037-4e27-a8d0-375f1a0f380c
Apr 11, 2019 8:48:48 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
[default-c5r21]: TaskArn: arn:aws:ecs:us-east-1:xxxxxxxxxxx:task/4a5ca5a6-b037-4e27-a8d0-375f1a0f380c
Apr 11, 2019 8:48:48 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
[default-c5r21]: TaskDefinitionArn: arn:aws:ecs:us-east-1:xxxxxxxxxxx:task-definition/default-fargate-template:1
Apr 11, 2019 8:48:48 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
[default-c5r21]: ClusterArn: arn:aws:ecs:us-east-1:xxxxxxxxxxx:cluster/default
Apr 11, 2019 8:48:48 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
[default-c5r21]: ContainerInstanceArn: null
Apr 11, 2019 8:48:48 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
[default-c5r21]: Waiting for agent to start
Apr 11, 2019 8:48:50 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
[default-c5r21]: Waiting for agent to start
Apr 11, 2019 8:48:51 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
[default-c5r21]: Waiting for agent to start
Apr 11, 2019 8:48:52 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
[default-c5r21]: Waiting for agent to start
Apr 11, 2019 8:48:54 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
[default-c5r21]: Waiting for agent to start
Apr 11, 2019 8:48:55 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch
[default-c5r21]: Waiting for agent to start
Apr 11, 2019 8:48:56 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSLauncher launch

Task Details:
Exit Code	143
Command	["-url","http://jenkins-dev-xxxxxxxx.us-west-1.elb.amazonaws.com/","-tunnel","jenkins-dev-xxxxxxxx.us-west-1.elb.amazonaws.com:5000","xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx","default-c5r21"]
Privileged	false

**Comment by ndesai15** [comment]
Where Can I see these logs? The only thing what I noticed after configuring template details here, that agent never comes online for fargate then i checked in aws which led me to conclusion that it never created a task definition.But for testing when I created task definition manually in aws for fargate & passed ARN of it rather specifying a template details, it spins up a fargate container agent in AWS.

**Comment by eranchetz** [comment]
Is there any workaround for this, is it even possible to use fargate as a slave?

**Comment by EdisonHarada** [comment]
That's my setup and it's working:
![image](https://user-images.githubusercontent.com/5961396/66835147-4a5c3800-ef5f-11e9-9919-22a8361b50a6.png)

Task Definition
```
{
  "ipcMode": null,
  "executionRoleArn": "arn:aws:iam::<your_account>:role/ecsTaskExecutionRole",
  "containerDefinitions": [
    {
      "dnsSearchDomains": null,
      "logConfiguration": {
        "logDriver": "awslogs",
        "secretOptions": null,
        "options": {
          "awslogs-group": "<your_log_group>",
          "awslogs-region": "<your_region>",
          "awslogs-stream-prefix": "ecs"
        }
      },
      "entryPoint": null,
      "portMappings": [],
      "command": null,
      "linuxParameters": null,
      "cpu": 0,
      "environment": [],
      "resourceRequirements": null,
      "ulimits": null,
      "dnsServers": null,
      "mountPoints": [],
      "workingDirectory": null,
      "secrets": null,
      "dockerSecurityOptions": null,
      "memory": null,
      "memoryReservation": null,
      "volumesFrom": [],
      "stopTimeout": null,
      "image": "<your_image>",
      "startTimeout": null,
      "firelensConfiguration": null,
      "dependsOn": null,
      "disableNetworking": null,
      "interactive": null,
      "healthCheck": null,
      "essential": true,
      "links": null,
      "hostname": null,
      "extraHosts": null,
      "pseudoTerminal": null,
      "user": null,
      "readonlyRootFilesystem": null,
      "dockerLabels": null,
      "systemControls": null,
      "privileged": null,
      "name": "jenkins"
    }
  ],
  "placementConstraints": [],
  "memory": "8192",
  "taskRoleArn": "arn:aws:iam::<your_account>:role/ecsTaskExecutionRole",
  "compatibilities": [
    "EC2",
    "FARGATE"
  ],
  "taskDefinitionArn": "arn:aws:ecs:<your_region>:<your_account>:task-definition/jenkins-slave:1",
  "family": "jenkins-slave",
  "requiresAttributes": [
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.logging-driver.awslogs"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "ecs.capability.execution-role-awslogs"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.ecr-auth"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.docker-remote-api.1.19"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.task-iam-role"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "ecs.capability.execution-role-ecr-pull"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.docker-remote-api.1.18"
    },
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "ecs.capability.task-eni"
    }
  ],
  "pidMode": null,
  "requiresCompatibilities": [
    "FARGATE"
  ],
  "networkMode": "awsvpc",
  "cpu": "4096",
  "revision": 1,
  "status": "ACTIVE",
  "inferenceAccelerators": null,
  "proxyConfiguration": null,
  "volumes": []
}
```

**Comment by jamescrowley321** [comment]
Yes, it is possible. One possible issue I see with the OP's screenshot is the memory/CPU settings - 256 Soft Memory and 1024 CPU. See here - https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-cpu-memory-error.html - for valid combinations. In my configuration, I also had to leave the Soft Memory setting at 0 and populate the Hard Memory setting.

**Comment by FnTm** [comment]
I can definitely confirm that it's possible to run tasks on Fargate without having to create the definitions in AWS. We've been doing that for at least 6 months now.
I can also confirm that it's possible to use the TaskDefinition override to provide an external task definition. 
So both of those modes work.

The mis-configuration of vCPU/Memory @jamescrowley321 mentions here has bit me in the past as well, but I don't think that's the case here. If the task managed to start and exit with 143, then that means that it did get started properly.

My only guess at this moment would be that the task that gets spun up can't communicate to Jenkins.
What you could try doing is changing the logging method for the Fargate container to be `awslogs`, which would let you read the log output of the task that is failing and get some ideas there.

**Comment by narendrachandrakar** [comment]
@FnTm please could provide more details, I am passing through TaskDefinition override, its trying to create slave, but getting "Waiting for agent to connect" message  in Jenkins system logs , do we need to handle any network connectivity b/n Jenkins & slave ??
could you share screen shot, if possible.

**Comment by FnTm** [comment]
@narendrachandrakar yes, you definitely need to make sure that the Jenkins agents can connect to master.
These are the most common reasons I can think of when I've had this issue in the past:
- The Fargate instance doesn't have the correct Security groups to communicate either to EC2 or to ECR to pull the image
- Same issue as above, but due to Network ACL's
- **The Fargate task may not have the Task Role defined which would allow it to pull the image from ECR**.  _A large number of face-palms have been done due to this_.

The way I've debugged this in the past is by looking in the ECS task logs about why it's failing. It's usually something to the effect of "Can't Pull the required image". This usually means networking/permission issue.
For bonus points you can specify an awslogs config in the Jenkins settings so that any agent CLI logs are sent to Cloudwatch and you can actually see what's going wrong. This has been of limited use to me thus far, but has saved my butt one time.
