### ISSUE TITLE
Declarative Override Fail - 1.20-beta2

### ISSUE THREAD

**Issue by alineprattiezops** [jenkinsci/amazon-ecs-plugin#92]
> Which version are you using? The declarative support comes with 1.20 with is currently in beta (1.20-beta2)

Please, could help us?
We install 1.20-beta2 but we are not having success in the declarative override:

pipeline {
  agent any
  stages {
    stage('Test') {
        agent {
          ecs {
            cloud 'cloud-default'
            label 'ecs'
            image 'jenkinsci/jnlp-slave'
            launchType 'FARGATE'
            memory 4096
            cpu 2048
            subnets 'subnet-xxxxxxxxxxxxx'
            securityGroups 'sg-xxxxxxxxxxx'
            assignPublicIp true
            taskrole 'arn:aws:iam::xxxxxxxxxxxxxxx:role/ecsTaskExecutionRole'
            inheritFrom 'fargate-template'
        }
    }
        steps {
            sh 'echo hello'
        }
    }
  }
}

Jenkins output:
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Test)
[Pipeline] ecsTaskTemplate
[Pipeline] // ecsTaskTemplate
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: Cloud does not exist: cloud-default
Finished: FAILURE

Jenkins Log:
Apr 11, 2019 9:13:08 PM INFO com.cloudbees.jenkins.plugins.amazonecs.pipeline.ECSDeclarativeAgent getAsArgs
In getAsArgs. label: ecs
Apr 11, 2019 9:13:08 PM INFO com.cloudbees.jenkins.plugins.amazonecs.pipeline.ECSDeclarativeAgent getAsArgs
In getAsArgs. argMap: {assignPublicIp=true, cloud=cloud-default, cpu=2048, image=jenkinsci/jnlp-slave, inheritFrom=fargate-template, label=ecs, launchType=FARGATE, memory=4096, name=ecs, overrides=[assignPublicIp, cloud, cpu, image, inheritFrom, label, launchType, memory, securityGroups, subnets, taskrole], privileged=false, securityGroups=sg-xxxxxxxx, subnets=subnet-xxxxxxxx, taskrole=arn:aws:iam::xxxxxxxx:role/ecsTaskExecutionRole}
Apr 11, 2019 9:13:08 PM INFO org.jenkinsci.plugins.workflow.job.WorkflowRun finish
test_pipeline #36 completed: FAILURE

_Originally posted by @alineprattiezops in https://github.com/jenkinsci/amazon-ecs-plugin/issues/84#issuecomment-482326963_

**Comment by pgarbe** [comment]
In your Jenkins settings (Manage Jenkins -> Configure System), did you set up a "Amazon EC2 Container Services Cloud" with name"default-cloud"? Maybe this is missing?
(Also commented in #84)

**Comment by haidaraM** [comment]
Getting the same error. I only have one Amazon EC2 Container Services Cloud named "ecs-cloud-jenkins". No "cloud-default". I have a template named "base-template" (it's not fargate). My allowed declarative settings is set to "all".

```groovy
pipeline {
  agent none
  
  stages {
    stage('Test') {
        agent {
            ecs {
                cpu 1024
                memory 512
                inheritFrom 'base-template'
            }
        }
        steps {
            sh 'echo hello'
        }
    }
  }
}
```

Jenkins 2.174
ECS Plugin: 1.20

**Comment by haidaraM** [comment]
Ok I got it. The example in the readme is a bit confusing about label and template. I have copied and pasted the example thinking `inheritFrom` is the template name...

This example works, `base` is a label:
```groovy
pipeline {
  agent none
  
  stages {
    stage('Test') {
        agent {
            ecs {
                cpu 1024
                memory 512
                inheritFrom 'base'
            }
        }
        steps {
            sh 'echo hello'
        }
    }
  }
}
```

**Comment by webratz** [comment]
Is this resolved for you now? Can it be closed?
