### ISSUE TITLE
Declarative Agent Declaration Doesn't Allow Using Fargate

### ISSUE THREAD

**Issue by giles-jason** [jenkinsci/amazon-ecs-plugin#95]
When using the declarative agent declaration to define or extend an agent with the Fargate launch type, the plugin fails to register the Task Definition with an error that states:

```
[jenkins-60gn8]: Error in provisioning; agent=com.cloudbees.jenkins.plugins.amazonecs.ECSSlave[jenkins-60gn8]
com.amazonaws.services.ecs.model.ClientException: Fargate requires task definition to have execution role ARN to support ECR images. (Service: AmazonECS; Status Code: 400; Error Code: ClientException; Request ID: eb36ec6a-6c41-11e9-ae73-89fda2289aa7)
```

Upon doing some digging, it looks like `com.cloudbees.jenkins.plugins.amazonecs.pipeline.ECSDeclarativeAgent` does not have a property for `executionRole` but `com.cloudbees.jenkins.plugins.amazonecs.ECSTaskTemplate` does. I believe this is leading to the execution role not being passed in the `RegisterTaskDefinition` call.

**Comment by pgarbe** [comment]
That's a good point. The executionRole is not (yet) supported with the declarative syntax. 

Also, during merge the executionRole [gets lost](https://github.com/jenkinsci/amazon-ecs-plugin/blob/master/src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate.java#L517-L575) when you inherit from a pre-defined configuration.
