### ISSUE TITLE
Plugins difference with scalable-amazon-ecs

### ISSUE THREAD

**Issue by JadyDJ** [jenkinsci/amazon-ecs-plugin#96]
What is the difference between this plugin vs Amazon EC2 Container Service with autoscaling capabilities? (https://plugins.jenkins.io/scalable-amazon-ecs)?

It is confused.

Thank you,

**Comment by pgarbe** [comment]
I don't know about the history of the other plugin. Just found out that the plugin you mentioned doesn't exist (or at least I couldn't find any code). 

What I can say for sure is that this plugin is actively developed and used.

**Comment by JadyDJ** [comment]
Thank you for the information
