### ISSUE TITLE
Pass dynamic environment variable

### ISSUE THREAD

**Issue by an-sush** [jenkinsci/amazon-ecs-plugin#97]
Hello,
Is it possible to send custom environment variable to the task definition? Say I have a jenkins pipeline which is trying to provision a slave and I wan to pass  the build_url to the docker container as env variable. It doesn't work if I set a new env variable as $BUILD_URL or System.getEnv("BUILD_URL").

**Comment by webratz** [comment]
Could you maybe explain the use case, to set the env variable for the whole docker container, and not using the Jenkins intermal ways to specify env vars?
As the agent resets and overrides the env vars anyway for created job, there is just a small point to where env variables attached to the container are actually accessible

**Comment by an-sush** [comment]
Hello, I am trying to capture docker stats (io used, time running etc) using sigterm signal. So just before the container exits, i capture these for reporting. What I am missing is the BUILD_URL variable which is present under the jenkins job (pipeline) as env variable but not as a env for docker conatiner. If I could use/pass it while container is starting, it would enhance my reporting.
