### ISSUE TITLE
Support swarm slaves

### ISSUE THREAD

**Issue by tstibbs** [jenkinsci/amazon-ecs-plugin#99]
I would like to use this plugin in conjunction with the swarm plugin, but I'm seeing some difficulties.

Rationale: Swarm slaves make it much easier to configure things like tool locations than the normal JNLP slaves, because you can pass this info on the command line to the swarm jar. Also, I already have a jenkins slave container that uses the swarm client, and it would make sense to use the same image across the ECS slaves and any other kind of slave.

Problem I'm seeing: I've managed to tweak the image to get it to be compatible with how this plugin launches the containers, so it does actually launch. However, this plugin registers a new slave before launching the container. This prevents the swarm slave from starting correctly, because it believes that the slave already exists. Swarm can be configured to delete the pre-existing slave if it has the same name, but that confuses the ECS plugin, because the slave it just created disappears, meaning it tries to register a new one (and it just continues round in the loop).

It's not obvious from looking at the code how to change this behaviour. It looks like the creation and deletion of the slaves is all part of the CloudSlave functionality in core jenkins - removing the creation without removing the deletion (which _is_ still required) may be difficult?

**Comment by pgarbe** [comment]
Can you share some details about the swarm slaves you're using?

**Comment by tstibbs** [comment]
Not sure what details you're looking for, but they're just containers that run a swarm slave on startup, with all of our usual tools in (e.g. jdk). The swarm slave is passed details of all the tools as command parameters, such that when it creates the slave in jenkins all the tool locations stuff is populated correctly (which appears to be much harder with a jnlp slave).

It's probably worth mentioning that I've pretty much got it working in <50 lines of pipeline script just calling the ECS api directly, and not using this plugin at all - so maybe trying to use this plugin is not the right approach for swarm slaves. Feel free to close the issue on that basis if you like.

**Comment by webratz** [comment]
I'd close that for now, as supporting swarm is not really the goal of the plugin.
Maube you still want to share your solution, so others could use it.

**Comment by tstibbs** [comment]
Unfortunately I can't share the code (commercial restrictions) but I suppose it doesn't do anything particularly inventive - just starts an ECS task, runs the build, then stops the ECS task again.
